// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, session_id, role, content, tool_calls, tool_call_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at
`

type CreateMessageParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	Role       string      `json:"role"`
	Content    string      `json:"content"`
	ToolCalls  []byte      `json:"tool_calls"`
	ToolCallID pgtype.Text `json:"tool_call_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.UserID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE user_id = $1 AND session_id = $2
`

type DeleteSessionMessagesParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) DeleteSessionMessages(ctx context.Context, arg DeleteSessionMessagesParams) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, arg.UserID, arg.SessionID)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at FROM (
  SELECT id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at FROM messages
  WHERE user_id = $1 AND session_id = $2
  ORDER BY created_at DESC
  LIMIT $3 OFFSET $4
) sub
ORDER BY created_at ASC
`

type GetMessagesParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages,
		arg.UserID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
