// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, session_id, role, content, tool_calls, tool_call_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at
`

type CreateMessageParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	Role       string      `json:"role"`
	Content    string      `json:"content"`
	ToolCalls  []byte      `json:"tool_calls"`
	ToolCallID pgtype.Text `json:"tool_call_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.UserID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const createPendingToolConfirmation = `-- name: CreatePendingToolConfirmation :one
INSERT INTO pending_tool_confirmations (user_id, session_id, tool_name, args_json, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, session_id, tool_name, args_json, status, created_at, resolved_at
`

type CreatePendingToolConfirmationParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ToolName  string      `json:"tool_name"`
	ArgsJson  []byte      `json:"args_json"`
}

func (q *Queries) CreatePendingToolConfirmation(ctx context.Context, arg CreatePendingToolConfirmationParams) (PendingToolConfirmation, error) {
	row := q.db.QueryRow(ctx, createPendingToolConfirmation,
		arg.UserID,
		arg.SessionID,
		arg.ToolName,
		arg.ArgsJson,
	)
	var i PendingToolConfirmation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ArgsJson,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE user_id = $1 AND session_id = $2
`

type DeleteSessionMessagesParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) DeleteSessionMessages(ctx context.Context, arg DeleteSessionMessagesParams) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, arg.UserID, arg.SessionID)
	return err
}

const deleteWorkingMemoryForSession = `-- name: DeleteWorkingMemoryForSession :exec
DELETE FROM agent_working_memory
WHERE user_id = $1 AND session_id = $2
`

type DeleteWorkingMemoryForSessionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) DeleteWorkingMemoryForSession(ctx context.Context, arg DeleteWorkingMemoryForSessionParams) error {
	_, err := q.db.Exec(ctx, deleteWorkingMemoryForSession, arg.UserID, arg.SessionID)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at FROM (
  SELECT id, user_id, session_id, role, content, tool_calls, tool_call_id, created_at FROM messages
  WHERE user_id = $1 AND session_id = $2
  ORDER BY created_at DESC
  LIMIT $3 OFFSET $4
) sub
ORDER BY created_at ASC
`

type GetMessagesParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages,
		arg.UserID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingToolConfirmation = `-- name: GetPendingToolConfirmation :one
SELECT id, user_id, session_id, tool_name, args_json, status, created_at, resolved_at
FROM pending_tool_confirmations
WHERE id = $1 AND user_id = $2
`

type GetPendingToolConfirmationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPendingToolConfirmation(ctx context.Context, arg GetPendingToolConfirmationParams) (PendingToolConfirmation, error) {
	row := q.db.QueryRow(ctx, getPendingToolConfirmation, arg.ID, arg.UserID)
	var i PendingToolConfirmation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ArgsJson,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getWorkingMemoryForSession = `-- name: GetWorkingMemoryForSession :many
SELECT key, value FROM agent_working_memory
WHERE user_id = $1 AND session_id = $2
`

type GetWorkingMemoryForSessionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type GetWorkingMemoryForSessionRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetWorkingMemoryForSession(ctx context.Context, arg GetWorkingMemoryForSessionParams) ([]GetWorkingMemoryForSessionRow, error) {
	rows, err := q.db.Query(ctx, getWorkingMemoryForSession, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkingMemoryForSessionRow
	for rows.Next() {
		var i GetWorkingMemoryForSessionRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkingMemoryValue = `-- name: GetWorkingMemoryValue :one
SELECT value FROM agent_working_memory
WHERE user_id = $1 AND session_id = $2 AND key = $3
`

type GetWorkingMemoryValueParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Key       string      `json:"key"`
}

func (q *Queries) GetWorkingMemoryValue(ctx context.Context, arg GetWorkingMemoryValueParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkingMemoryValue, arg.UserID, arg.SessionID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const resolvePendingToolConfirmation = `-- name: ResolvePendingToolConfirmation :one
UPDATE pending_tool_confirmations
SET status = $3, resolved_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, user_id, session_id, tool_name, args_json, status, created_at, resolved_at
`

type ResolvePendingToolConfirmationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
}

func (q *Queries) ResolvePendingToolConfirmation(ctx context.Context, arg ResolvePendingToolConfirmationParams) (PendingToolConfirmation, error) {
	row := q.db.QueryRow(ctx, resolvePendingToolConfirmation, arg.ID, arg.UserID, arg.Status)
	var i PendingToolConfirmation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ArgsJson,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setWorkingMemoryValue = `-- name: SetWorkingMemoryValue :one
INSERT INTO agent_working_memory (user_id, session_id, key, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, session_id, key) DO UPDATE SET 
    value = EXCLUDED.value,
    updated_at = NOW()
RETURNING user_id, session_id, key, value, created_at, updated_at
`

type SetWorkingMemoryValueParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Key       string      `json:"key"`
	Value     string      `json:"value"`
}

func (q *Queries) SetWorkingMemoryValue(ctx context.Context, arg SetWorkingMemoryValueParams) (AgentWorkingMemory, error) {
	row := q.db.QueryRow(ctx, setWorkingMemoryValue,
		arg.UserID,
		arg.SessionID,
		arg.Key,
		arg.Value,
	)
	var i AgentWorkingMemory
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
