// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countMemories = `-- name: CountMemories :one
SELECT COUNT(*) FROM memories
WHERE user_id = $1
`

func (q *Queries) CountMemories(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemories, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (user_id, content, embedding)
VALUES ($1, $2, $3)
RETURNING id, user_id, content, embedding, created_at, updated_at
`

type CreateMemoryParams struct {
	UserID    pgtype.UUID     `json:"user_id"`
	Content   string          `json:"content"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory, arg.UserID, arg.Content, arg.Embedding)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories
WHERE id = $1 AND user_id = $2
`

type DeleteMemoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.UserID)
	return err
}

const getMemories = `-- name: GetMemories :many
SELECT id, user_id, content, embedding, created_at, updated_at FROM memories
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMemoriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetMemories(ctx context.Context, arg GetMemoriesParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, getMemories, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryableEmbeddings = `-- name: GetRetryableEmbeddings :many
SELECT n.id, n.content, n.user_id 
FROM notes n
WHERE (n.embedding_status = 'pending'
   OR (n.embedding_status = 'failed' AND n.updated_at < NOW() - INTERVAL '5 minutes'))
  AND n.deleted_at IS NULL
  AND NOT n.is_inbox
LIMIT $1
`

type GetRetryableEmbeddingsRow struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRetryableEmbeddings(ctx context.Context, limit int32) ([]GetRetryableEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, getRetryableEmbeddings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRetryableEmbeddingsRow
	for rows.Next() {
		var i GetRetryableEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.Content, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSoul = `-- name: GetSoul :one
SELECT id, user_id, personality, created_at, updated_at, profile FROM souls
WHERE user_id = $1
`

func (q *Queries) GetSoul(ctx context.Context, userID pgtype.UUID) (Soul, error) {
	row := q.db.QueryRow(ctx, getSoul, userID)
	var i Soul
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Personality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Profile,
	)
	return i, err
}

const searchMemoriesByEmbedding = `-- name: SearchMemoriesByEmbedding :many
SELECT m.id, m.content, m.created_at, (1 - (m.embedding <=> $2::vector))::real AS similarity
FROM memories m
WHERE m.user_id = $1
ORDER BY m.embedding <=> $2::vector
LIMIT $3
`

type SearchMemoriesByEmbeddingParams struct {
	UserID  pgtype.UUID     `json:"user_id"`
	Column2 pgvector.Vector `json:"column_2"`
	Limit   int32           `json:"limit"`
}

type SearchMemoriesByEmbeddingRow struct {
	ID         pgtype.UUID        `json:"id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Similarity float32            `json:"similarity"`
}

func (q *Queries) SearchMemoriesByEmbedding(ctx context.Context, arg SearchMemoriesByEmbeddingParams) ([]SearchMemoriesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchMemoriesByEmbedding, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesByEmbeddingRow
	for rows.Next() {
		var i SearchMemoriesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesByEmbedding = `-- name: SearchNotesByEmbedding :many
SELECT n.id, regexp_replace(split_part(n.content, E'\n', 1), '^(#+\s*|[-*]\s*(\[[ xX]\]\s*)?|\d+\.\s*)', '') AS title, n.content, n.updated_at, (1 - (ne.embedding <=> $2::vector))::real AS similarity
FROM notes n
JOIN note_embeddings ne ON n.id = ne.note_id
WHERE n.user_id = $1 AND n.deleted_at IS NULL AND NOT n.is_inbox
ORDER BY ne.embedding <=> $2::vector
LIMIT $3
`

type SearchNotesByEmbeddingParams struct {
	UserID  pgtype.UUID     `json:"user_id"`
	Column2 pgvector.Vector `json:"column_2"`
	Limit   int32           `json:"limit"`
}

type SearchNotesByEmbeddingRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Similarity float32            `json:"similarity"`
}

func (q *Queries) SearchNotesByEmbedding(ctx context.Context, arg SearchNotesByEmbeddingParams) ([]SearchNotesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchNotesByEmbedding, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesByEmbeddingRow
	for rows.Next() {
		var i SearchNotesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories
SET content = $2, embedding = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, content, embedding, created_at, updated_at
`

type UpdateMemoryParams struct {
	ID        pgtype.UUID     `json:"id"`
	Content   string          `json:"content"`
	Embedding pgvector.Vector `json:"embedding"`
	UserID    pgtype.UUID     `json:"user_id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.ID,
		arg.Content,
		arg.Embedding,
		arg.UserID,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNoteEmbeddingStatus = `-- name: UpdateNoteEmbeddingStatus :exec
UPDATE notes
SET embedding_status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNoteEmbeddingStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	EmbeddingStatus string      `json:"embedding_status"`
}

func (q *Queries) UpdateNoteEmbeddingStatus(ctx context.Context, arg UpdateNoteEmbeddingStatusParams) error {
	_, err := q.db.Exec(ctx, updateNoteEmbeddingStatus, arg.ID, arg.EmbeddingStatus)
	return err
}

const updateSoulProfile = `-- name: UpdateSoulProfile :one
UPDATE souls
SET profile = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, personality, created_at, updated_at, profile
`

type UpdateSoulProfileParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Profile []byte      `json:"profile"`
}

func (q *Queries) UpdateSoulProfile(ctx context.Context, arg UpdateSoulProfileParams) (Soul, error) {
	row := q.db.QueryRow(ctx, updateSoulProfile, arg.UserID, arg.Profile)
	var i Soul
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Personality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Profile,
	)
	return i, err
}

const upsertNoteEmbedding = `-- name: UpsertNoteEmbedding :exec
INSERT INTO note_embeddings (note_id, embedding)
VALUES ($1, $2)
ON CONFLICT (note_id) DO UPDATE SET 
    embedding = EXCLUDED.embedding,
    updated_at = NOW()
`

type UpsertNoteEmbeddingParams struct {
	NoteID    pgtype.UUID     `json:"note_id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpsertNoteEmbedding(ctx context.Context, arg UpsertNoteEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertNoteEmbedding, arg.NoteID, arg.Embedding)
	return err
}

const upsertSoul = `-- name: UpsertSoul :one
INSERT INTO souls (user_id, personality)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET 
    personality = EXCLUDED.personality,
    updated_at = NOW()
RETURNING id, user_id, personality, created_at, updated_at, profile
`

type UpsertSoulParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Personality string      `json:"personality"`
}

func (q *Queries) UpsertSoul(ctx context.Context, arg UpsertSoulParams) (Soul, error) {
	row := q.db.QueryRow(ctx, upsertSoul, arg.UserID, arg.Personality)
	var i Soul
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Personality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Profile,
	)
	return i, err
}
