// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alexa.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAlexaRequestIdempotency = `-- name: CompleteAlexaRequestIdempotency :execrows
UPDATE alexa_request_idempotency
SET status = 'completed',
    response_json = $4,
    expires_at = $5,
    updated_at = NOW()
WHERE application_id = $1
  AND request_id = $2
  AND owner_token = $3
  AND status = 'pending'
`

type CompleteAlexaRequestIdempotencyParams struct {
	ApplicationID string             `json:"application_id"`
	RequestID     string             `json:"request_id"`
	OwnerToken    string             `json:"owner_token"`
	ResponseJson  []byte             `json:"response_json"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CompleteAlexaRequestIdempotency(ctx context.Context, arg CompleteAlexaRequestIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAlexaRequestIdempotency,
		arg.ApplicationID,
		arg.RequestID,
		arg.OwnerToken,
		arg.ResponseJson,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAlexaRequestIdempotency = `-- name: DeleteExpiredAlexaRequestIdempotency :exec
DELETE FROM alexa_request_idempotency
WHERE status = 'completed' AND expires_at <= NOW()
`

func (q *Queries) DeleteExpiredAlexaRequestIdempotency(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAlexaRequestIdempotency)
	return err
}

const getAlexaRequestIdempotencyForUpdate = `-- name: GetAlexaRequestIdempotencyForUpdate :one
SELECT application_id, request_id, fingerprint, status, response_json,
       owner_token, lease_until, expires_at, created_at, updated_at
FROM alexa_request_idempotency
WHERE application_id = $1 AND request_id = $2
FOR UPDATE
`

type GetAlexaRequestIdempotencyForUpdateParams struct {
	ApplicationID string `json:"application_id"`
	RequestID     string `json:"request_id"`
}

func (q *Queries) GetAlexaRequestIdempotencyForUpdate(ctx context.Context, arg GetAlexaRequestIdempotencyForUpdateParams) (AlexaRequestIdempotency, error) {
	row := q.db.QueryRow(ctx, getAlexaRequestIdempotencyForUpdate, arg.ApplicationID, arg.RequestID)
	var i AlexaRequestIdempotency
	err := row.Scan(
		&i.ApplicationID,
		&i.RequestID,
		&i.Fingerprint,
		&i.Status,
		&i.ResponseJson,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlexaRequestIdempotency = `-- name: InsertAlexaRequestIdempotency :one
INSERT INTO alexa_request_idempotency
    (application_id, request_id, fingerprint, status, owner_token, lease_until)
VALUES ($1, $2, $3, 'pending', $4, $5)
ON CONFLICT (application_id, request_id) DO NOTHING
RETURNING application_id, request_id, fingerprint, status, response_json,
          owner_token, lease_until, expires_at, created_at, updated_at
`

type InsertAlexaRequestIdempotencyParams struct {
	ApplicationID string             `json:"application_id"`
	RequestID     string             `json:"request_id"`
	Fingerprint   string             `json:"fingerprint"`
	OwnerToken    string             `json:"owner_token"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) InsertAlexaRequestIdempotency(ctx context.Context, arg InsertAlexaRequestIdempotencyParams) (AlexaRequestIdempotency, error) {
	row := q.db.QueryRow(ctx, insertAlexaRequestIdempotency,
		arg.ApplicationID,
		arg.RequestID,
		arg.Fingerprint,
		arg.OwnerToken,
		arg.LeaseUntil,
	)
	var i AlexaRequestIdempotency
	err := row.Scan(
		&i.ApplicationID,
		&i.RequestID,
		&i.Fingerprint,
		&i.Status,
		&i.ResponseJson,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reuseExpiredAlexaRequestIdempotency = `-- name: ReuseExpiredAlexaRequestIdempotency :one
UPDATE alexa_request_idempotency
SET fingerprint = $3,
    status = 'pending',
    response_json = NULL,
    owner_token = $4,
    lease_until = $5,
    expires_at = NULL,
    updated_at = NOW()
WHERE application_id = $1
  AND request_id = $2
  AND status = 'completed'
  AND expires_at <= NOW()
RETURNING application_id, request_id, fingerprint, status, response_json,
          owner_token, lease_until, expires_at, created_at, updated_at
`

type ReuseExpiredAlexaRequestIdempotencyParams struct {
	ApplicationID string             `json:"application_id"`
	RequestID     string             `json:"request_id"`
	Fingerprint   string             `json:"fingerprint"`
	OwnerToken    string             `json:"owner_token"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) ReuseExpiredAlexaRequestIdempotency(ctx context.Context, arg ReuseExpiredAlexaRequestIdempotencyParams) (AlexaRequestIdempotency, error) {
	row := q.db.QueryRow(ctx, reuseExpiredAlexaRequestIdempotency,
		arg.ApplicationID,
		arg.RequestID,
		arg.Fingerprint,
		arg.OwnerToken,
		arg.LeaseUntil,
	)
	var i AlexaRequestIdempotency
	err := row.Scan(
		&i.ApplicationID,
		&i.RequestID,
		&i.Fingerprint,
		&i.Status,
		&i.ResponseJson,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takeOverAlexaRequestIdempotency = `-- name: TakeOverAlexaRequestIdempotency :one
UPDATE alexa_request_idempotency
SET owner_token = $3,
    lease_until = $4,
    updated_at = NOW()
WHERE application_id = $1
  AND request_id = $2
  AND status = 'pending'
  AND lease_until <= NOW()
RETURNING application_id, request_id, fingerprint, status, response_json,
          owner_token, lease_until, expires_at, created_at, updated_at
`

type TakeOverAlexaRequestIdempotencyParams struct {
	ApplicationID string             `json:"application_id"`
	RequestID     string             `json:"request_id"`
	OwnerToken    string             `json:"owner_token"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
}

func (q *Queries) TakeOverAlexaRequestIdempotency(ctx context.Context, arg TakeOverAlexaRequestIdempotencyParams) (AlexaRequestIdempotency, error) {
	row := q.db.QueryRow(ctx, takeOverAlexaRequestIdempotency, arg.ApplicationID, arg.RequestID, arg.OwnerToken, arg.LeaseUntil)
	var i AlexaRequestIdempotency
	err := row.Scan(
		&i.ApplicationID,
		&i.RequestID,
		&i.Fingerprint,
		&i.Status,
		&i.ResponseJson,
		&i.OwnerToken,
		&i.LeaseUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
