// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const enqueueAttachmentDeletion = `-- name: EnqueueAttachmentDeletion :exec
WITH storage_key_lock AS (
    SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
)
INSERT INTO attachment_deletion_outbox (storage_key)
SELECT $1
FROM storage_key_lock
WHERE NOT EXISTS (
    SELECT 1 FROM attachments WHERE storage_key = $1
)
ON CONFLICT DO NOTHING
`

func (q *Queries) EnqueueAttachmentDeletion(ctx context.Context, storageKey string) error {
	_, err := q.db.Exec(ctx, enqueueAttachmentDeletion, storageKey)
	return err
}

const claimAttachmentDeletion = `-- name: ClaimAttachmentDeletion :one
SELECT id, storage_key, referenced
FROM claim_attachment_storage_deletion($1)
`

type ClaimAttachmentDeletionParams struct {
	StorageKey pgtype.Text `json:"storage_key"`
}

type ClaimAttachmentDeletionRow struct {
	ID         pgtype.UUID `json:"id"`
	StorageKey string      `json:"storage_key"`
	Referenced bool        `json:"referenced"`
}

func (q *Queries) ClaimAttachmentDeletion(ctx context.Context, arg ClaimAttachmentDeletionParams) (ClaimAttachmentDeletionRow, error) {
	row := q.db.QueryRow(ctx, claimAttachmentDeletion, arg.StorageKey)
	var i ClaimAttachmentDeletionRow
	err := row.Scan(&i.ID, &i.StorageKey, &i.Referenced)
	return i, err
}

const completeAttachmentDeletion = `-- name: CompleteAttachmentDeletion :exec
DELETE FROM attachment_deletion_outbox
WHERE id = $1
`

func (q *Queries) CompleteAttachmentDeletion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeAttachmentDeletion, id)
	return err
}

const retryAttachmentDeletion = `-- name: RetryAttachmentDeletion :exec
UPDATE attachment_deletion_outbox
SET status = 'pending',
    available_at = NOW() + INTERVAL '1 minute',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
`

type RetryAttachmentDeletionParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError string      `json:"last_error"`
}

func (q *Queries) RetryAttachmentDeletion(ctx context.Context, arg RetryAttachmentDeletionParams) error {
	_, err := q.db.Exec(ctx, retryAttachmentDeletion, arg.ID, arg.LastError)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, note_id, filename, storage_key, mime_type, size_bytes, created_at FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Filename,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
WITH storage_key_lock AS (
    SELECT pg_advisory_xact_lock(hashtextextended($3, 0))
), available_key AS (
    SELECT $1 AS note_id, $2 AS filename, $3 AS storage_key,
           $4 AS mime_type, $5 AS size_bytes
    FROM storage_key_lock
    WHERE NOT EXISTS (
        SELECT 1
        FROM attachment_deletion_outbox
        WHERE storage_key = $3
          AND status IN ('pending', 'processing')
    )
)
INSERT INTO attachments (note_id, filename, storage_key, mime_type, size_bytes)
SELECT note_id, filename, storage_key, mime_type, size_bytes
FROM available_key
RETURNING id, note_id, filename, storage_key, mime_type, size_bytes, created_at
`

type InsertAttachmentParams struct {
	NoteID     pgtype.UUID `json:"note_id"`
	Filename   string      `json:"filename"`
	StorageKey string      `json:"storage_key"`
	MimeType   string      `json:"mime_type"`
	SizeBytes  int64       `json:"size_bytes"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.NoteID,
		arg.Filename,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Filename,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByNote = `-- name: ListAttachmentsByNote :many
SELECT id, note_id, filename, storage_key, mime_type, size_bytes, created_at FROM attachments
WHERE note_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByNote(ctx context.Context, noteID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Filename,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
