// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (note_id, filename, url, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, note_id, filename, url, mime_type, size_bytes, created_at
`

type InsertAttachmentParams struct {
	NoteID    pgtype.UUID `json:"note_id"`
	Filename  string      `json:"filename"`
	Url       string      `json:"url"`
	MimeType  string      `json:"mime_type"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.NoteID,
		arg.Filename,
		arg.Url,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.Filename,
		&i.Url,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByNote = `-- name: ListAttachmentsByNote :many
SELECT id, note_id, filename, url, mime_type, size_bytes, created_at FROM attachments
WHERE note_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByNote(ctx context.Context, noteID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.Filename,
			&i.Url,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
