// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Attachment struct {
	ID        pgtype.UUID        `json:"id"`
	NoteID    pgtype.UUID        `json:"note_id"`
	Filename  string             `json:"filename"`
	Url       string             `json:"url"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int64              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Context struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DeviceToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SessionID  pgtype.UUID        `json:"session_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	ToolCalls  []byte             `json:"tool_calls"`
	ToolCallID pgtype.Text        `json:"tool_call_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Title           pgtype.Text        `json:"title"`
	Content         string             `json:"content"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	IsInbox         bool               `json:"is_inbox"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
	SearchVector    []byte             `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	EmbeddingStatus string             `json:"embedding_status"`
}

type NoteEmbedding struct {
	ID        pgtype.UUID        `json:"id"`
	NoteID    pgtype.UUID        `json:"note_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NoteLink struct {
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type NoteTag struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Routine struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	CronExpr  string             `json:"cron_expr"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Name      string             `json:"name"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	BriefType string             `json:"brief_type"`
}

type RoutineLog struct {
	ID        pgtype.UUID        `json:"id"`
	RoutineID pgtype.UUID        `json:"routine_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Status    string             `json:"status"`
	Content   pgtype.Text        `json:"content"`
	ErrorMsg  pgtype.Text        `json:"error_msg"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Soul struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Personality string             `json:"personality"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID         pgtype.UUID        `json:"id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	Recurrence pgtype.Text        `json:"recurrence"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type TaskCompletion struct {
	ID          pgtype.UUID        `json:"id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Status      string             `json:"status"`
}

type TelegramLink struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	TelegramChatID   int64              `json:"telegram_chat_id"`
	TelegramUsername pgtype.Text        `json:"telegram_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TelegramLinkCode struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
