// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM note_nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNodesByNoteId = `-- name: GetNodesByNoteId :many
SELECT id, note_id, parent_id, position, type, data, created_at, updated_at FROM note_nodes WHERE note_id = $1 ORDER BY position ASC
`

func (q *Queries) GetNodesByNoteId(ctx context.Context, noteID pgtype.UUID) ([]NoteNode, error) {
	rows, err := q.db.Query(ctx, getNodesByNoteId, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteNode
	for rows.Next() {
		var i NoteNode
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.ParentID,
			&i.Position,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNode = `-- name: InsertNode :one
INSERT INTO note_nodes (id, note_id, parent_id, position, type, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, note_id, parent_id, position, type, data, created_at, updated_at
`

type InsertNodeParams struct {
	ID       pgtype.UUID `json:"id"`
	NoteID   pgtype.UUID `json:"note_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
	Type     string      `json:"type"`
	Data     []byte      `json:"data"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (NoteNode, error) {
	row := q.db.QueryRow(ctx, insertNode,
		arg.ID,
		arg.NoteID,
		arg.ParentID,
		arg.Position,
		arg.Type,
		arg.Data,
	)
	var i NoteNode
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE note_nodes
SET position = $2, data = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, note_id, parent_id, position, type, data, created_at, updated_at
`

type UpdateNodeParams struct {
	ID       pgtype.UUID `json:"id"`
	Position int32       `json:"position"`
	Data     []byte      `json:"data"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (NoteNode, error) {
	row := q.db.QueryRow(ctx, updateNode, arg.ID, arg.Position, arg.Data)
	var i NoteNode
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
