// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_operations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNotePermission = `-- name: CheckNotePermission :one
SELECT COALESCE(
  (SELECT 'owner'::text FROM notes WHERE notes.id = $1 AND notes.user_id = $2 AND notes.deleted_at IS NULL),
  (SELECT permission::text FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2),
  'none'::text
) AS permission
`

type CheckNotePermissionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckNotePermission(ctx context.Context, arg CheckNotePermissionParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, checkNotePermission, arg.ID, arg.UserID)
	var permission interface{}
	err := row.Scan(&permission)
	return permission, err
}

const getLastOperation = `-- name: GetLastOperation :one
SELECT note_id, revision, operation_id, actor_id, base_revision, kind, block_id, payload, created_at FROM note_operations
WHERE note_id = $1
ORDER BY revision DESC
LIMIT 1
`

func (q *Queries) GetLastOperation(ctx context.Context, noteID pgtype.UUID) (NoteOperation, error) {
	row := q.db.QueryRow(ctx, getLastOperation, noteID)
	var i NoteOperation
	err := row.Scan(
		&i.NoteID,
		&i.Revision,
		&i.OperationID,
		&i.ActorID,
		&i.BaseRevision,
		&i.Kind,
		&i.BlockID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getNoteDocument = `-- name: GetNoteDocument :one
SELECT revision, document FROM notes WHERE id = $1 AND deleted_at IS NULL
`

type GetNoteDocumentRow struct {
	Revision int64  `json:"revision"`
	Document []byte `json:"document"`
}

func (q *Queries) GetNoteDocument(ctx context.Context, id pgtype.UUID) (GetNoteDocumentRow, error) {
	row := q.db.QueryRow(ctx, getNoteDocument, id)
	var i GetNoteDocumentRow
	err := row.Scan(&i.Revision, &i.Document)
	return i, err
}

const getNoteOperationByOpID = `-- name: GetNoteOperationByOpID :one
SELECT note_id, revision, operation_id, actor_id, base_revision, kind, block_id, payload, created_at FROM note_operations
WHERE note_id = $1 AND operation_id = $2
`

type GetNoteOperationByOpIDParams struct {
	NoteID      pgtype.UUID `json:"note_id"`
	OperationID pgtype.UUID `json:"operation_id"`
}

func (q *Queries) GetNoteOperationByOpID(ctx context.Context, arg GetNoteOperationByOpIDParams) (NoteOperation, error) {
	row := q.db.QueryRow(ctx, getNoteOperationByOpID, arg.NoteID, arg.OperationID)
	var i NoteOperation
	err := row.Scan(
		&i.NoteID,
		&i.Revision,
		&i.OperationID,
		&i.ActorID,
		&i.BaseRevision,
		&i.Kind,
		&i.BlockID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getOperationsSince = `-- name: GetOperationsSince :many
SELECT note_id, revision, operation_id, actor_id, base_revision, kind, block_id, payload, created_at FROM note_operations
WHERE note_id = $1 AND revision > $2
ORDER BY revision
`

type GetOperationsSinceParams struct {
	NoteID   pgtype.UUID `json:"note_id"`
	Revision int64       `json:"revision"`
}

func (q *Queries) GetOperationsSince(ctx context.Context, arg GetOperationsSinceParams) ([]NoteOperation, error) {
	rows, err := q.db.Query(ctx, getOperationsSince, arg.NoteID, arg.Revision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteOperation
	for rows.Next() {
		var i NoteOperation
		if err := rows.Scan(
			&i.NoteID,
			&i.Revision,
			&i.OperationID,
			&i.ActorID,
			&i.BaseRevision,
			&i.Kind,
			&i.BlockID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOperation = `-- name: InsertOperation :one
INSERT INTO note_operations (note_id, revision, operation_id, actor_id, base_revision, kind, block_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING note_id, revision, operation_id, actor_id, base_revision, kind, block_id, payload, created_at
`

type InsertOperationParams struct {
	NoteID       pgtype.UUID `json:"note_id"`
	Revision     int64       `json:"revision"`
	OperationID  pgtype.UUID `json:"operation_id"`
	ActorID      pgtype.UUID `json:"actor_id"`
	BaseRevision int64       `json:"base_revision"`
	Kind         string      `json:"kind"`
	BlockID      pgtype.Text `json:"block_id"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) (NoteOperation, error) {
	row := q.db.QueryRow(ctx, insertOperation,
		arg.NoteID,
		arg.Revision,
		arg.OperationID,
		arg.ActorID,
		arg.BaseRevision,
		arg.Kind,
		arg.BlockID,
		arg.Payload,
	)
	var i NoteOperation
	err := row.Scan(
		&i.NoteID,
		&i.Revision,
		&i.OperationID,
		&i.ActorID,
		&i.BaseRevision,
		&i.Kind,
		&i.BlockID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const lockNote = `-- name: LockNote :one
SELECT id, revision, document, snapshot_revision
FROM notes
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type LockNoteRow struct {
	ID               pgtype.UUID `json:"id"`
	Revision         int64       `json:"revision"`
	Document         []byte      `json:"document"`
	SnapshotRevision int64       `json:"snapshot_revision"`
}

func (q *Queries) LockNote(ctx context.Context, id pgtype.UUID) (LockNoteRow, error) {
	row := q.db.QueryRow(ctx, lockNote, id)
	var i LockNoteRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Document,
		&i.SnapshotRevision,
	)
	return i, err
}

const updateNoteDocument = `-- name: UpdateNoteDocument :exec
UPDATE notes
SET document = $2, revision = $3, content = $4, excerpt = $5, snapshot_revision = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateNoteDocumentParams struct {
	ID               pgtype.UUID `json:"id"`
	Document         []byte      `json:"document"`
	Revision         int64       `json:"revision"`
	Content          string      `json:"content"`
	Excerpt          pgtype.Text `json:"excerpt"`
	SnapshotRevision int64       `json:"snapshot_revision"`
}

func (q *Queries) UpdateNoteDocument(ctx context.Context, arg UpdateNoteDocumentParams) error {
	_, err := q.db.Exec(ctx, updateNoteDocument,
		arg.ID,
		arg.Document,
		arg.Revision,
		arg.Content,
		arg.Excerpt,
		arg.SnapshotRevision,
	)
	return err
}
