// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToNote = `-- name: AddTagToNote :exec
INSERT INTO note_tags (note_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToNoteParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.Exec(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const appendToNoteContent = `-- name: AppendToNoteContent :one
UPDATE notes
SET content = content || E'\n\n' || $3, updated_at = NOW()
WHERE notes.id = $1 AND notes.deleted_at IS NULL
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2 AND note_shares.permission = 'edit'))
RETURNING id, user_id, context_id, content, excerpt, search_vector, created_at, updated_at, deleted_at, embedding_status, collapse_images
`

type AppendToNoteContentParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) AppendToNoteContent(ctx context.Context, arg AppendToNoteContentParams) (Note, error) {
	row := q.db.QueryRow(ctx, appendToNoteContent, arg.ID, arg.UserID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Content,
		&i.Excerpt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.CollapseImages,
	)
	return i, err
}

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNotes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (user_id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, slug, name, created_at, updated_at, deleted_at
`

type CreateContextParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Slug   string      `json:"slug"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext, arg.UserID, arg.Slug, arg.Name)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, context_id, content, embedding_status, collapse_images)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, context_id, content, excerpt, search_vector, created_at, updated_at, deleted_at, embedding_status, collapse_images
`

type CreateNoteParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	ContextID       pgtype.UUID `json:"context_id"`
	Content         string      `json:"content"`
	EmbeddingStatus string      `json:"embedding_status"`
	CollapseImages  bool        `json:"collapse_images"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.ContextID,
		arg.Content,
		arg.EmbeddingStatus,
		arg.CollapseImages,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Content,
		&i.Excerpt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.CollapseImages,
	)
	return i, err
}

const createNoteLink = `-- name: CreateNoteLink :exec
INSERT INTO note_links (source_id, target_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateNoteLinkParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error {
	_, err := q.db.Exec(ctx, createNoteLink, arg.SourceID, arg.TargetID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContext = `-- name: DeleteContext :exec
DELETE FROM contexts
WHERE id = $1 AND user_id = $2
`

type DeleteContextParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteContext(ctx context.Context, arg DeleteContextParams) error {
	_, err := q.db.Exec(ctx, deleteContext, arg.ID, arg.UserID)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getAllNotesForMigration = `-- name: GetAllNotesForMigration :many
SELECT id, content FROM notes WHERE content IS NOT NULL AND content != ''
`

type GetAllNotesForMigrationRow struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) GetAllNotesForMigration(ctx context.Context) ([]GetAllNotesForMigrationRow, error) {
	rows, err := q.db.Query(ctx, getAllNotesForMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNotesForMigrationRow
	for rows.Next() {
		var i GetAllNotesForMigrationRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContexts = `-- name: GetContexts :many
SELECT id, user_id, slug, name, created_at, updated_at, deleted_at FROM contexts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetContexts(ctx context.Context, userID pgtype.UUID) ([]Context, error) {
	rows, err := q.db.Query(ctx, getContexts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Context
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedNotes = `-- name: GetLinkedNotes :many
SELECT DISTINCT n.id, n.user_id, n.context_id, n.content, n.excerpt, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.collapse_images FROM notes n
JOIN note_links nl ON (n.id = nl.source_id OR n.id = nl.target_id)
WHERE (nl.source_id = ANY($1::uuid[]) OR nl.target_id = ANY($1::uuid[]))
  AND n.id != ALL($1::uuid[])
  AND n.user_id = $2
  AND n.deleted_at IS NULL
LIMIT 5
`

type GetLinkedNotesParams struct {
	Column1 []pgtype.UUID `json:"column_1"`
	UserID  pgtype.UUID   `json:"user_id"`
}

func (q *Queries) GetLinkedNotes(ctx context.Context, arg GetLinkedNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getLinkedNotes, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Content,
			&i.Excerpt,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.CollapseImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT n.id, n.user_id, n.context_id, n.content, n.excerpt, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.collapse_images,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $2
WHERE n.id = $1 AND n.deleted_at IS NULL
  AND (n.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2))
`

type GetNoteByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetNoteByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Content         string             `json:"content"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	SearchVector    pgtype.Text        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	EmbeddingStatus string             `json:"embedding_status"`
	CollapseImages  bool               `json:"collapse_images"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Content,
		&i.Excerpt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.CollapseImages,
		&i.Favorite,
		&i.Archived,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT n.id, n.user_id, n.context_id, n.content, n.excerpt, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.collapse_images,
  COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $1
WHERE n.deleted_at IS NULL
  AND (n.user_id = $1 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = n.id AND note_shares.user_id = $1))
  AND ($2::uuid IS NULL OR n.context_id = $2)
  AND ($3::boolean IS NULL OR COALESCE(unp.favorite, FALSE) = $3)
  AND ($4::timestamptz IS NULL OR n.updated_at < $4 OR (n.updated_at = $4 AND n.id < $5))
ORDER BY n.updated_at DESC, n.id DESC
LIMIT $6
`

type GetNotesParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Favorite        pgtype.Bool        `json:"favorite"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

type GetNotesRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Content         string             `json:"content"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	SearchVector    pgtype.Text        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	EmbeddingStatus string             `json:"embedding_status"`
	CollapseImages  bool               `json:"collapse_images"`
	Title           string             `json:"title"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]GetNotesRow, error) {
	rows, err := q.db.Query(ctx, getNotes,
		arg.UserID,
		arg.ContextID,
		arg.Favorite,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesRow
	for rows.Next() {
		var i GetNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Content,
			&i.Excerpt,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.CollapseImages,
			&i.Title,
			&i.Favorite,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentNotes = `-- name: GetRecentNotes :many
SELECT n.id, n.user_id, n.context_id, n.content, n.excerpt, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.collapse_images,
  COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $1
WHERE n.user_id = $1
  AND n.deleted_at IS NULL
  AND n.updated_at >= NOW() - INTERVAL '48 hours'
ORDER BY n.updated_at DESC
LIMIT 10
`

type GetRecentNotesRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Content         string             `json:"content"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	SearchVector    pgtype.Text        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	EmbeddingStatus string             `json:"embedding_status"`
	CollapseImages  bool               `json:"collapse_images"`
	Title           string             `json:"title"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
}

func (q *Queries) GetRecentNotes(ctx context.Context, userID pgtype.UUID) ([]GetRecentNotesRow, error) {
	rows, err := q.db.Query(ctx, getRecentNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentNotesRow
	for rows.Next() {
		var i GetRecentNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Content,
			&i.Excerpt,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.CollapseImages,
			&i.Title,
			&i.Favorite,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTags = `-- name: GetTags :many
SELECT id, user_id, name, created_at FROM tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.user_id, t.name, t.created_at FROM tags t
JOIN note_tags nt ON t.id = nt.tag_id
WHERE nt.note_id = $1
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromNote = `-- name: RemoveTagFromNote :exec
DELETE FROM note_tags
WHERE note_id = $1 AND tag_id = $2
`

type RemoveTagFromNoteParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error {
	_, err := q.db.Exec(ctx, removeTagFromNote, arg.NoteID, arg.TagID)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = COALESCE($3, content),
    context_id = COALESCE($4, context_id),
    embedding_status = COALESCE($5, embedding_status),
    collapse_images = COALESCE($6, collapse_images),
    updated_at = NOW()
WHERE notes.id = $1 AND notes.deleted_at IS NULL
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2 AND note_shares.permission = 'edit'))
RETURNING id, user_id, context_id, content, excerpt, search_vector, created_at, updated_at, deleted_at, embedding_status, collapse_images
`

type UpdateNoteParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Content         pgtype.Text `json:"content"`
	ContextID       pgtype.UUID `json:"context_id"`
	EmbeddingStatus pgtype.Text `json:"embedding_status"`
	CollapseImages  pgtype.Bool `json:"collapse_images"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.ContextID,
		arg.EmbeddingStatus,
		arg.CollapseImages,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Content,
		&i.Excerpt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.CollapseImages,
	)
	return i, err
}

const updateNoteSearchVector = `-- name: UpdateNoteSearchVector :exec
UPDATE notes SET search_vector = $2 WHERE id = $1
`

type UpdateNoteSearchVectorParams struct {
	ID           pgtype.UUID `json:"id"`
	SearchVector pgtype.Text `json:"search_vector"`
}

func (q *Queries) UpdateNoteSearchVector(ctx context.Context, arg UpdateNoteSearchVectorParams) error {
	_, err := q.db.Exec(ctx, updateNoteSearchVector, arg.ID, arg.SearchVector)
	return err
}

const updateNotesContentFromNodes = `-- name: UpdateNotesContentFromNodes :exec
UPDATE notes n
SET content = (
    SELECT COALESCE(string_agg(
        CASE 
            WHEN type = 'header' THEN repeat('#', COALESCE((data->>'level')::int, 1)) || ' ' || COALESCE(data->>'text', '')
            WHEN type = 'task' THEN '- [' || CASE WHEN (data->>'completed')::boolean = TRUE THEN 'x' ELSE ' ' END || '] ' || COALESCE(data->>'text', '')
            WHEN type = 'list_item' THEN '- ' || COALESCE(data->>'text', '')
            ELSE COALESCE(data->>'text', '')
        END,
        E'\n' ORDER BY position
    ), '')
    FROM note_nodes
    WHERE note_id = n.id AND deleted_at IS NULL
)
WHERE n.id = ANY($1::uuid[])
`

func (q *Queries) UpdateNotesContentFromNodes(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateNotesContentFromNodes, dollar_1)
	return err
}
