// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNotes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, content, collapse_images)
VALUES ($1, $2, $3)
RETURNING id, user_id, content, excerpt, created_at, updated_at, deleted_at, collapse_images, revision, document, snapshot_revision
`

type CreateNoteParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Content        string      `json:"content"`
	CollapseImages bool        `json:"collapse_images"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Content, arg.CollapseImages)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CollapseImages,
		&i.Revision,
		&i.Document,
		&i.SnapshotRevision,
	)
	return i, err
}

const createNoteLink = `-- name: CreateNoteLink :exec
INSERT INTO note_links (source_id, target_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateNoteLinkParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error {
	_, err := q.db.Exec(ctx, createNoteLink, arg.SourceID, arg.TargetID)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getAllNotesForMigration = `-- name: GetAllNotesForMigration :many
SELECT id, content FROM notes WHERE content IS NOT NULL AND content != ''
`

type GetAllNotesForMigrationRow struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) GetAllNotesForMigration(ctx context.Context) ([]GetAllNotesForMigrationRow, error) {
	rows, err := q.db.Query(ctx, getAllNotesForMigration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNotesForMigrationRow
	for rows.Next() {
		var i GetAllNotesForMigrationRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedNotes = `-- name: GetLinkedNotes :many
SELECT DISTINCT n.id, n.user_id, n.content, n.excerpt, n.created_at, n.updated_at, n.deleted_at, n.collapse_images, n.revision, n.document, n.snapshot_revision FROM notes n
JOIN note_links nl ON (n.id = nl.source_id OR n.id = nl.target_id)
WHERE (nl.source_id = ANY($1::uuid[]) OR nl.target_id = ANY($1::uuid[]))
  AND n.id != ALL($1::uuid[])
  AND n.user_id = $2
  AND n.deleted_at IS NULL
LIMIT 5
`

type GetLinkedNotesParams struct {
	Column1 []pgtype.UUID `json:"column_1"`
	UserID  pgtype.UUID   `json:"user_id"`
}

func (q *Queries) GetLinkedNotes(ctx context.Context, arg GetLinkedNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getLinkedNotes, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Excerpt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CollapseImages,
			&i.Revision,
			&i.Document,
			&i.SnapshotRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT n.id, n.user_id, n.content, n.excerpt, n.created_at, n.updated_at, n.deleted_at, n.collapse_images, n.revision, n.document, n.snapshot_revision,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $2
WHERE n.id = $1 AND n.deleted_at IS NULL
  AND (n.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2))
`

type GetNoteByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetNoteByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Content          string             `json:"content"`
	Excerpt          pgtype.Text        `json:"excerpt"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CollapseImages   bool               `json:"collapse_images"`
	Revision         int64              `json:"revision"`
	Document         []byte             `json:"document"`
	SnapshotRevision int64              `json:"snapshot_revision"`
	Favorite         bool               `json:"favorite"`
	Archived         bool               `json:"archived"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CollapseImages,
		&i.Revision,
		&i.Document,
		&i.SnapshotRevision,
		&i.Favorite,
		&i.Archived,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT
  n.id, n.user_id,
  n.excerpt,
  n.created_at, n.updated_at, n.deleted_at,
  n.collapse_images,
  NULLIF(regexp_replace(split_part(n.content, E'\n', 1), '^#+\s*', ''), '')::text AS title,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $1
WHERE n.deleted_at IS NULL
  AND (n.user_id = $1 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = n.id AND note_shares.user_id = $1))
  AND ($2::boolean IS NULL OR COALESCE(unp.favorite, FALSE) = $2)
  AND ($3::timestamptz IS NULL OR n.updated_at < $3 OR (n.updated_at = $3 AND n.id < $4))
ORDER BY n.updated_at DESC, n.id DESC
LIMIT $5
`

type GetNotesParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Favorite        pgtype.Bool        `json:"favorite"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

type GetNotesRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CollapseImages bool               `json:"collapse_images"`
	Title          string             `json:"title"`
	Favorite       bool               `json:"favorite"`
	Archived       bool               `json:"archived"`
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]GetNotesRow, error) {
	rows, err := q.db.Query(ctx, getNotes,
		arg.UserID,
		arg.Favorite,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesRow
	for rows.Next() {
		var i GetNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Excerpt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CollapseImages,
			&i.Title,
			&i.Favorite,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentNotes = `-- name: GetRecentNotes :many
SELECT
  n.id, n.user_id,
  n.excerpt,
  n.created_at, n.updated_at, n.deleted_at,
  n.collapse_images,
  NULLIF(regexp_replace(split_part(n.content, E'\n', 1), '^#+\s*', ''), '')::text AS title,
  COALESCE(unp.favorite, FALSE)::boolean AS favorite,
  COALESCE(unp.archived, FALSE)::boolean AS archived
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $1
WHERE n.user_id = $1
  AND n.deleted_at IS NULL
  AND n.updated_at >= NOW() - INTERVAL '48 hours'
ORDER BY n.updated_at DESC
LIMIT 10
`

type GetRecentNotesRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CollapseImages bool               `json:"collapse_images"`
	Title          string             `json:"title"`
	Favorite       bool               `json:"favorite"`
	Archived       bool               `json:"archived"`
}

func (q *Queries) GetRecentNotes(ctx context.Context, userID pgtype.UUID) ([]GetRecentNotesRow, error) {
	rows, err := q.db.Query(ctx, getRecentNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentNotesRow
	for rows.Next() {
		var i GetRecentNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Excerpt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CollapseImages,
			&i.Title,
			&i.Favorite,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteOldNotes = `-- name: HardDeleteOldNotes :exec
DELETE FROM notes
WHERE deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteOldNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteOldNotes)
	return err
}

const tryAcquireGCLock = `-- name: TryAcquireGCLock :one
SELECT pg_try_advisory_xact_lock(hashtext('gc_notes_lock')) AS acquired
`

func (q *Queries) TryAcquireGCLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireGCLock)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = COALESCE($3, content),
    collapse_images = COALESCE($4, collapse_images),
    updated_at = NOW()
WHERE notes.id = $1 AND notes.deleted_at IS NULL
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2 AND note_shares.permission = 'edit'))
RETURNING id, user_id, content, excerpt, created_at, updated_at, deleted_at, collapse_images, revision, document, snapshot_revision
`

type UpdateNoteParams struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	Content        pgtype.Text `json:"content"`
	CollapseImages pgtype.Bool `json:"collapse_images"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.CollapseImages,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CollapseImages,
		&i.Revision,
		&i.Document,
		&i.SnapshotRevision,
	)
	return i, err
}

const updateNoteContent = `-- name: UpdateNoteContent :exec
UPDATE notes SET content = $2, excerpt = COALESCE(substring($2 FROM 1 FOR 200), ''), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

type UpdateNoteContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) error {
	_, err := q.db.Exec(ctx, updateNoteContent, arg.ID, arg.Content)
	return err
}
