// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToNote = `-- name: AddTagToNote :exec
INSERT INTO note_tags (note_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToNoteParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.Exec(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const appendToInbox = `-- name: AppendToInbox :one
UPDATE notes
SET content = content || E'\n\n' || $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND is_inbox = true AND deleted_at IS NULL
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type AppendToInboxParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) AppendToInbox(ctx context.Context, arg AppendToInboxParams) (Note, error) {
	row := q.db.QueryRow(ctx, appendToInbox, arg.ID, arg.UserID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const appendToNoteContent = `-- name: AppendToNoteContent :one
UPDATE notes
SET content = content || E'\n\n' || $3, updated_at = NOW()
WHERE notes.id = $1 AND notes.deleted_at IS NULL AND notes.is_inbox = false
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2 AND note_shares.permission = 'edit'))
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type AppendToNoteContentParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) AppendToNoteContent(ctx context.Context, arg AppendToNoteContentParams) (Note, error) {
	row := q.db.QueryRow(ctx, appendToNoteContent, arg.ID, arg.UserID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes WHERE user_id = $1 AND deleted_at IS NULL AND NOT is_inbox
`

func (q *Queries) CountNotes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (user_id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, slug, name, created_at, updated_at
`

type CreateContextParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Slug   string      `json:"slug"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext, arg.UserID, arg.Slug, arg.Name)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, context_id, title, content, is_inbox, favorite, archived, embedding_status, hide_completed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type CreateNoteParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	ContextID       pgtype.UUID `json:"context_id"`
	Title           pgtype.Text `json:"title"`
	Content         string      `json:"content"`
	IsInbox         bool        `json:"is_inbox"`
	Favorite        bool        `json:"favorite"`
	Archived        bool        `json:"archived"`
	EmbeddingStatus string      `json:"embedding_status"`
	HideCompleted   bool        `json:"hide_completed"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.ContextID,
		arg.Title,
		arg.Content,
		arg.IsInbox,
		arg.Favorite,
		arg.Archived,
		arg.EmbeddingStatus,
		arg.HideCompleted,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const createNoteLink = `-- name: CreateNoteLink :exec
INSERT INTO note_links (source_id, target_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateNoteLinkParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error {
	_, err := q.db.Exec(ctx, createNoteLink, arg.SourceID, arg.TargetID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContext = `-- name: DeleteContext :exec
DELETE FROM contexts
WHERE id = $1 AND user_id = $2
`

type DeleteContextParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteContext(ctx context.Context, arg DeleteContextParams) error {
	_, err := q.db.Exec(ctx, deleteContext, arg.ID, arg.UserID)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getContexts = `-- name: GetContexts :many
SELECT id, user_id, slug, name, created_at, updated_at FROM contexts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetContexts(ctx context.Context, userID pgtype.UUID) ([]Context, error) {
	rows, err := q.db.Query(ctx, getContexts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Context
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboxNote = `-- name: GetInboxNote :one
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed FROM notes
WHERE user_id = $1 AND is_inbox = true AND deleted_at IS NULL
`

func (q *Queries) GetInboxNote(ctx context.Context, userID pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getInboxNote, userID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const getLinkedNotes = `-- name: GetLinkedNotes :many
SELECT DISTINCT n.id, n.user_id, n.context_id, n.title, n.content, n.excerpt, n.is_inbox, n.favorite, n.archived, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.hide_completed FROM notes n
JOIN note_links nl ON (n.id = nl.source_id OR n.id = nl.target_id)
WHERE (nl.source_id = ANY($1::uuid[]) OR nl.target_id = ANY($1::uuid[]))
  AND n.id != ALL($1::uuid[])
  AND n.user_id = $2
  AND n.deleted_at IS NULL
  AND n.is_inbox = false
LIMIT 5
`

type GetLinkedNotesParams struct {
	Column1 []pgtype.UUID `json:"column_1"`
	UserID  pgtype.UUID   `json:"user_id"`
}

func (q *Queries) GetLinkedNotes(ctx context.Context, arg GetLinkedNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getLinkedNotes, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.HideCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed FROM notes
WHERE notes.id = $1 AND notes.deleted_at IS NULL
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2))
`

type GetNoteByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed FROM notes
WHERE is_inbox = false
  AND deleted_at IS NULL
  AND (notes.user_id = $1 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = notes.id AND note_shares.user_id = $1))
  AND ($2::uuid IS NULL OR context_id = $2)
  AND ($3::boolean IS NULL OR favorite = $3)
  AND ($4::timestamptz IS NULL OR notes.updated_at < $4 OR (notes.updated_at = $4 AND notes.id < $5))
ORDER BY notes.updated_at DESC, notes.id DESC
LIMIT $6
`

type GetNotesParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Favorite        pgtype.Bool        `json:"favorite"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getNotes,
		arg.UserID,
		arg.ContextID,
		arg.Favorite,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.HideCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentNotes = `-- name: GetRecentNotes :many
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed FROM notes
WHERE user_id = $1
  AND is_inbox = false
  AND deleted_at IS NULL
  AND updated_at >= NOW() - INTERVAL '48 hours'
ORDER BY updated_at DESC
LIMIT 10
`

func (q *Queries) GetRecentNotes(ctx context.Context, userID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, getRecentNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.HideCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTags = `-- name: GetTags :many
SELECT id, user_id, name, created_at FROM tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.user_id, t.name, t.created_at FROM tags t
JOIN note_tags nt ON t.id = nt.tag_id
WHERE nt.note_id = $1
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromNote = `-- name: RemoveTagFromNote :exec
DELETE FROM note_tags
WHERE note_id = $1 AND tag_id = $2
`

type RemoveTagFromNoteParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error {
	_, err := q.db.Exec(ctx, removeTagFromNote, arg.NoteID, arg.TagID)
	return err
}

const setInboxContent = `-- name: SetInboxContent :one
UPDATE notes
SET content = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND is_inbox = true AND deleted_at IS NULL
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type SetInboxContentParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) SetInboxContent(ctx context.Context, arg SetInboxContentParams) (Note, error) {
	row := q.db.QueryRow(ctx, setInboxContent, arg.ID, arg.UserID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = COALESCE($3, title),
    content = COALESCE($4, content),
    context_id = COALESCE($5, context_id),
    favorite = COALESCE($6, favorite),
    archived = COALESCE($7, archived),
    embedding_status = COALESCE($8, embedding_status),
    hide_completed = COALESCE($9, hide_completed),
    updated_at = NOW()
WHERE notes.id = $1 AND notes.deleted_at IS NULL
  AND (notes.user_id = $2 OR EXISTS (SELECT 1 FROM note_shares WHERE note_shares.note_id = $1 AND note_shares.user_id = $2 AND note_shares.permission = 'edit'))
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type UpdateNoteParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Title           pgtype.Text `json:"title"`
	Content         pgtype.Text `json:"content"`
	ContextID       pgtype.UUID `json:"context_id"`
	Favorite        pgtype.Bool `json:"favorite"`
	Archived        pgtype.Bool `json:"archived"`
	EmbeddingStatus pgtype.Text `json:"embedding_status"`
	HideCompleted   pgtype.Bool `json:"hide_completed"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ContextID,
		arg.Favorite,
		arg.Archived,
		arg.EmbeddingStatus,
		arg.HideCompleted,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}
