// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckNotePermission(ctx context.Context, arg CheckNotePermissionParams) (interface{}, error)
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	CountNotes(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error
	CreateNoteShare(ctx context.Context, arg CreateNoteShareParams) (NoteShare, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRotatedRefreshToken(ctx context.Context, arg CreateRotatedRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error)
	DeleteAttachment(ctx context.Context, id pgtype.UUID) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteNoteShare(ctx context.Context, arg DeleteNoteShareParams) error
	DisableNoteShareLink(ctx context.Context, noteID pgtype.UUID) error
	GetAllNotesForMigration(ctx context.Context) ([]GetAllNotesForMigrationRow, error)
	GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error)
	GetLastOperation(ctx context.Context, noteID pgtype.UUID) (NoteOperation, error)
	GetLinkedNotes(ctx context.Context, arg GetLinkedNotesParams) ([]Note, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error)
	GetNoteDocument(ctx context.Context, id pgtype.UUID) (GetNoteDocumentRow, error)
	GetNoteOperationByOpID(ctx context.Context, arg GetNoteOperationByOpIDParams) (NoteOperation, error)
	GetNoteOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetNoteShareForUser(ctx context.Context, arg GetNoteShareForUserParams) (NoteShare, error)
	GetNoteShareLink(ctx context.Context, noteID pgtype.UUID) (NoteShareLink, error)
	GetNoteShares(ctx context.Context, noteID pgtype.UUID) ([]GetNoteSharesRow, error)
	GetNotes(ctx context.Context, arg GetNotesParams) ([]GetNotesRow, error)
	GetOperationsSince(ctx context.Context, arg GetOperationsSinceParams) ([]NoteOperation, error)
	GetPublicNoteByShareToken(ctx context.Context, tokenID pgtype.UUID) (GetPublicNoteByShareTokenRow, error)
	GetPublicNoteIDByShareToken(ctx context.Context, tokenID pgtype.UUID) (pgtype.UUID, error)
	GetRecentNotes(ctx context.Context, userID pgtype.UUID) ([]GetRecentNotesRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenRecord(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSharedLinkIngestion(ctx context.Context, arg GetSharedLinkIngestionParams) (SharedLinkIngestion, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error)
	HardDeleteOldNotes(ctx context.Context) error
	InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error)
	InsertOperation(ctx context.Context, arg InsertOperationParams) (NoteOperation, error)
	ListAttachmentsByNote(ctx context.Context, noteID pgtype.UUID) ([]Attachment, error)
	LockNote(ctx context.Context, id pgtype.UUID) (LockNoteRow, error)
	ReserveSharedLinkIngestion(ctx context.Context, arg ReserveSharedLinkIngestionParams) (SharedLinkIngestion, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	TryAcquireGCLock(ctx context.Context) (bool, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) error
	UpdateNoteDocument(ctx context.Context, arg UpdateNoteDocumentParams) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
	UpsertNoteShareLink(ctx context.Context, arg UpsertNoteShareLinkParams) (NoteShareLink, error)
	UpsertUserNotePreference(ctx context.Context, arg UpsertUserNotePreferenceParams) (UserNotePreference, error)
}

var _ Querier = (*Queries)(nil)
