// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error
	AppendToInbox(ctx context.Context, arg AppendToInboxParams) (Note, error)
	AppendToNoteContent(ctx context.Context, arg AppendToNoteContentParams) (Note, error)
	CleanupOldMessages(ctx context.Context) error
	CountCompletedTasks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountNotes(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountOpenTasks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountTasks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateContext(ctx context.Context, arg CreateContextParams) (Context, error)
	CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error)
	CreateRoutineLog(ctx context.Context, arg CreateRoutineLogParams) (RoutineLog, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskCompletion(ctx context.Context, arg CreateTaskCompletionParams) (TaskCompletion, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error)
	DeleteContext(ctx context.Context, arg DeleteContextParams) error
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteSessionMessages(ctx context.Context, arg DeleteSessionMessagesParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetContexts(ctx context.Context, userID pgtype.UUID) ([]Context, error)
	GetEnabledRoutines(ctx context.Context) ([]GetEnabledRoutinesRow, error)
	GetInboxNote(ctx context.Context, userID pgtype.UUID) (Note, error)
	GetLatestBriefByType(ctx context.Context, arg GetLatestBriefByTypeParams) (RoutineLog, error)
	GetLinkedNotes(ctx context.Context, arg GetLinkedNotesParams) ([]Note, error)
	GetMemories(ctx context.Context, arg GetMemoriesParams) ([]Memory, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error)
	GetNotes(ctx context.Context, arg GetNotesParams) ([]Note, error)
	GetPendingEmbeddings(ctx context.Context, limit int32) ([]GetPendingEmbeddingsRow, error)
	GetRecentNotes(ctx context.Context, userID pgtype.UUID) ([]Note, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRetryableEmbeddings(ctx context.Context, limit int32) ([]GetRetryableEmbeddingsRow, error)
	GetRoutineLogsByUser(ctx context.Context, arg GetRoutineLogsByUserParams) ([]RoutineLog, error)
	GetRoutinesByUser(ctx context.Context, userID pgtype.UUID) ([]Routine, error)
	GetSoul(ctx context.Context, userID pgtype.UUID) (Soul, error)
	GetSyncContexts(ctx context.Context, arg GetSyncContextsParams) ([]Context, error)
	GetSyncNotes(ctx context.Context, arg GetSyncNotesParams) ([]Note, error)
	GetSyncTags(ctx context.Context, arg GetSyncTagsParams) ([]Tag, error)
	GetSyncTaskCompletions(ctx context.Context, arg GetSyncTaskCompletionsParams) ([]TaskCompletion, error)
	GetSyncTasks(ctx context.Context, arg GetSyncTasksParams) ([]Task, error)
	GetTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	GetTagsForNote(ctx context.Context, noteID pgtype.UUID) ([]Tag, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error)
	GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error)
	GetTasksByNoteID(ctx context.Context, arg GetTasksByNoteIDParams) ([]Task, error)
	GetTodayTasks(ctx context.Context, arg GetTodayTasksParams) ([]Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error)
	HardDeleteExpiredContexts(ctx context.Context) error
	HardDeleteExpiredNotes(ctx context.Context) error
	HardDeleteExpiredTasks(ctx context.Context) error
	ListDeviceTokensByUser(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error)
	RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SearchMemoriesByEmbedding(ctx context.Context, arg SearchMemoriesByEmbeddingParams) ([]SearchMemoriesByEmbeddingRow, error)
	SearchNotesByEmbedding(ctx context.Context, arg SearchNotesByEmbeddingParams) ([]SearchNotesByEmbeddingRow, error)
	SearchNotesFTS(ctx context.Context, arg SearchNotesFTSParams) ([]SearchNotesFTSRow, error)
	SearchNotesHybrid(ctx context.Context, arg SearchNotesHybridParams) ([]SearchNotesHybridRow, error)
	SearchNotesSemantic(ctx context.Context, arg SearchNotesSemanticParams) ([]SearchNotesSemanticRow, error)
	SetInboxContent(ctx context.Context, arg SetInboxContentParams) (Note, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateNoteEmbeddingStatus(ctx context.Context, arg UpdateNoteEmbeddingStatusParams) error
	UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error)
	UpdateRoutineLastRunAt(ctx context.Context, id pgtype.UUID) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
	UpsertContext(ctx context.Context, arg UpsertContextParams) (Context, error)
	UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error)
	UpsertNoteEmbedding(ctx context.Context, arg UpsertNoteEmbeddingParams) error
	UpsertSoul(ctx context.Context, arg UpsertSoulParams) (Soul, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
	UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error)
	// Inserts a completion row only if the parent task belongs to the user
	// (the SELECT returns 0 rows otherwise, making the INSERT a no-op).
	// Completions are append-only history; existing rows are never updated.
	UpsertTaskCompletion(ctx context.Context, arg UpsertTaskCompletionParams) error
}

var _ Querier = (*Queries)(nil)
