// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldMessages = `-- name: CleanupOldMessages :exec
DELETE FROM messages
WHERE created_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) CleanupOldMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldMessages)
	return err
}

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (user_id, type, cron_expr, enabled, name, brief_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, cron_expr, enabled, created_at, updated_at, name, last_run_at, brief_type, time_of_day, days_of_week
`

type CreateRoutineParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Type      string      `json:"type"`
	CronExpr  string      `json:"cron_expr"`
	Enabled   bool        `json:"enabled"`
	Name      string      `json:"name"`
	BriefType string      `json:"brief_type"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine,
		arg.UserID,
		arg.Type,
		arg.CronExpr,
		arg.Enabled,
		arg.Name,
		arg.BriefType,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.LastRunAt,
		&i.BriefType,
		&i.TimeOfDay,
		&i.DaysOfWeek,
	)
	return i, err
}

const createRoutineLog = `-- name: CreateRoutineLog :one
INSERT INTO routine_logs (routine_id, user_id, status, content, error_msg)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, routine_id, user_id, status, content, error_msg, created_at, telegram_sent_at
`

type CreateRoutineLogParams struct {
	RoutineID pgtype.UUID `json:"routine_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Status    string      `json:"status"`
	Content   pgtype.Text `json:"content"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
}

func (q *Queries) CreateRoutineLog(ctx context.Context, arg CreateRoutineLogParams) (RoutineLog, error) {
	row := q.db.QueryRow(ctx, createRoutineLog,
		arg.RoutineID,
		arg.UserID,
		arg.Status,
		arg.Content,
		arg.ErrorMsg,
	)
	var i RoutineLog
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.UserID,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.TelegramSentAt,
	)
	return i, err
}

const getEnabledRoutines = `-- name: GetEnabledRoutines :many
SELECT r.id, r.user_id, r.type, r.cron_expr, r.enabled, s.timezone
FROM routines r
JOIN user_settings s ON r.user_id = s.user_id
WHERE r.enabled = true
`

type GetEnabledRoutinesRow struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Type     string      `json:"type"`
	CronExpr string      `json:"cron_expr"`
	Enabled  bool        `json:"enabled"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) GetEnabledRoutines(ctx context.Context) ([]GetEnabledRoutinesRow, error) {
	rows, err := q.db.Query(ctx, getEnabledRoutines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnabledRoutinesRow
	for rows.Next() {
		var i GetEnabledRoutinesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.CronExpr,
			&i.Enabled,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBriefByType = `-- name: GetLatestBriefByType :one
SELECT rl.id, rl.routine_id, rl.user_id, rl.status, rl.content, rl.error_msg, rl.created_at, rl.telegram_sent_at FROM routine_logs rl
JOIN routines r ON rl.routine_id = r.id
WHERE rl.user_id = $1 AND r.type = $2 AND rl.status = 'success'
ORDER BY rl.created_at DESC
LIMIT 1
`

type GetLatestBriefByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) GetLatestBriefByType(ctx context.Context, arg GetLatestBriefByTypeParams) (RoutineLog, error) {
	row := q.db.QueryRow(ctx, getLatestBriefByType, arg.UserID, arg.Type)
	var i RoutineLog
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.UserID,
		&i.Status,
		&i.Content,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.TelegramSentAt,
	)
	return i, err
}

const getRoutineLogsByUser = `-- name: GetRoutineLogsByUser :many
SELECT id, routine_id, user_id, status, content, error_msg, created_at, telegram_sent_at FROM routine_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRoutineLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetRoutineLogsByUser(ctx context.Context, arg GetRoutineLogsByUserParams) ([]RoutineLog, error) {
	rows, err := q.db.Query(ctx, getRoutineLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutineLog
	for rows.Next() {
		var i RoutineLog
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.UserID,
			&i.Status,
			&i.Content,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.TelegramSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutinesByUser = `-- name: GetRoutinesByUser :many
SELECT id, user_id, type, cron_expr, enabled, created_at, updated_at, name, last_run_at, brief_type, time_of_day, days_of_week FROM routines
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRoutinesByUser(ctx context.Context, userID pgtype.UUID) ([]Routine, error) {
	rows, err := q.db.Query(ctx, getRoutinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.CronExpr,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.LastRunAt,
			&i.BriefType,
			&i.TimeOfDay,
			&i.DaysOfWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoutine = `-- name: UpdateRoutine :one
UPDATE routines
SET cron_expr = COALESCE($3, cron_expr),
    enabled = COALESCE($4, enabled),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, cron_expr, enabled, created_at, updated_at, name, last_run_at, brief_type, time_of_day, days_of_week
`

type UpdateRoutineParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	CronExpr pgtype.Text `json:"cron_expr"`
	Enabled  pgtype.Bool `json:"enabled"`
}

func (q *Queries) UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, updateRoutine,
		arg.ID,
		arg.UserID,
		arg.CronExpr,
		arg.Enabled,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.LastRunAt,
		&i.BriefType,
		&i.TimeOfDay,
		&i.DaysOfWeek,
	)
	return i, err
}

const updateRoutineLastRunAt = `-- name: UpdateRoutineLastRunAt :exec
UPDATE routines SET last_run_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateRoutineLastRunAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateRoutineLastRunAt, id)
	return err
}
