// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const searchNotesFTS = `-- name: SearchNotesFTS :many
SELECT n.id, COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title, n.content, n.excerpt, n.updated_at, n.context_id,
       COALESCE(unp.favorite, FALSE) AS favorite,
       COALESCE(unp.archived, FALSE) AS archived,
       ts_rank(n.search_vector, plainto_tsquery('simple', $1::text)) AS score
FROM notes n
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $2
WHERE n.user_id = $2
  AND n.deleted_at IS NULL 
  AND COALESCE(unp.archived, FALSE) = false
  AND n.search_vector @@ plainto_tsquery('simple', $1::text)
ORDER BY score DESC
LIMIT $3
`

type SearchNotesFTSParams struct {
	Query  string      `json:"query"`
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type SearchNotesFTSRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Excerpt   pgtype.Text        `json:"excerpt"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ContextID pgtype.UUID        `json:"context_id"`
	Favorite  bool               `json:"favorite"`
	Archived  bool               `json:"archived"`
	Score     float32            `json:"score"`
}

func (q *Queries) SearchNotesFTS(ctx context.Context, arg SearchNotesFTSParams) ([]SearchNotesFTSRow, error) {
	rows, err := q.db.Query(ctx, searchNotesFTS, arg.Query, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesFTSRow
	for rows.Next() {
		var i SearchNotesFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.UpdatedAt,
			&i.ContextID,
			&i.Favorite,
			&i.Archived,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesHybrid = `-- name: SearchNotesHybrid :many
WITH fts AS (
  SELECT n.id, COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title, n.content, n.excerpt, n.updated_at, n.context_id,
         COALESCE(unp.favorite, FALSE) AS favorite,
         COALESCE(unp.archived, FALSE) AS archived,
         row_number() OVER (ORDER BY ts_rank(n.search_vector, to_tsquery('simple', $2::text)) DESC) as rank
  FROM notes n
  LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $3
  WHERE n.user_id = $3
    AND n.deleted_at IS NULL 
    AND COALESCE(unp.archived, FALSE) = false
    AND n.search_vector @@ to_tsquery('simple', $2::text)
  LIMIT $4::int
),
semantic AS (
  SELECT n.id, COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title, n.content, n.excerpt, n.updated_at, n.context_id,
         COALESCE(unp.favorite, FALSE) AS favorite,
         COALESCE(unp.archived, FALSE) AS archived,
         row_number() OVER (ORDER BY ne.embedding <=> $5::vector) as rank
  FROM notes n
  JOIN note_embeddings ne ON n.id = ne.note_id
  LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $3
  WHERE n.user_id = $3
    AND n.deleted_at IS NULL 
    AND COALESCE(unp.archived, FALSE) = false
  LIMIT $6::int
)
SELECT 
  COALESCE(fts.id, semantic.id) as id,
  COALESCE(fts.title, semantic.title) as title,
  COALESCE(fts.content, semantic.content) as content,
  COALESCE(fts.excerpt, semantic.excerpt) as excerpt,
  COALESCE(fts.updated_at, semantic.updated_at) as updated_at,
  COALESCE(fts.context_id, semantic.context_id) as context_id,
  COALESCE(fts.favorite, semantic.favorite) as favorite,
  COALESCE(fts.archived, semantic.archived) as archived,
  (COALESCE(1.0 / (60.0 + fts.rank), 0.0) + COALESCE(1.0 / (60.0 + semantic.rank), 0.0))::float8 AS score
FROM fts
FULL OUTER JOIN semantic ON fts.id = semantic.id
ORDER BY score DESC
LIMIT $1::int
`

type SearchNotesHybridParams struct {
	Limit         int32           `json:"limit"`
	Query         string          `json:"query"`
	UserID        pgtype.UUID     `json:"user_id"`
	FtsLimit      int32           `json:"fts_limit"`
	Embedding     pgvector.Vector `json:"embedding"`
	SemanticLimit int32           `json:"semantic_limit"`
}

type SearchNotesHybridRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Excerpt   pgtype.Text        `json:"excerpt"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ContextID pgtype.UUID        `json:"context_id"`
	Favorite  bool               `json:"favorite"`
	Archived  bool               `json:"archived"`
	Score     float64            `json:"score"`
}

func (q *Queries) SearchNotesHybrid(ctx context.Context, arg SearchNotesHybridParams) ([]SearchNotesHybridRow, error) {
	rows, err := q.db.Query(ctx, searchNotesHybrid,
		arg.Limit,
		arg.Query,
		arg.UserID,
		arg.FtsLimit,
		arg.Embedding,
		arg.SemanticLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesHybridRow
	for rows.Next() {
		var i SearchNotesHybridRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.UpdatedAt,
			&i.ContextID,
			&i.Favorite,
			&i.Archived,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesSemantic = `-- name: SearchNotesSemantic :many
SELECT n.id, COALESCE((SELECT (nn.data->>'text')::text FROM note_nodes nn WHERE nn.note_id = n.id AND nn.deleted_at IS NULL AND nn.data->>'text' IS NOT NULL AND nn.data->>'text' <> '' ORDER BY nn.position ASC LIMIT 1), 'Untitled')::text AS title, n.content, n.excerpt, n.updated_at, n.context_id,
       COALESCE(unp.favorite, FALSE) AS favorite,
       COALESCE(unp.archived, FALSE) AS archived,
       (1.0 - (ne.embedding <=> $1::vector))::float8 AS score
FROM notes n
JOIN note_embeddings ne ON n.id = ne.note_id
LEFT JOIN user_note_preferences unp ON unp.note_id = n.id AND unp.user_id = $2
WHERE n.user_id = $2
  AND n.deleted_at IS NULL 
  AND COALESCE(unp.archived, FALSE) = false
ORDER BY ne.embedding <=> $1::vector
LIMIT $3
`

type SearchNotesSemanticParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	UserID    pgtype.UUID     `json:"user_id"`
	Limit     int32           `json:"limit"`
}

type SearchNotesSemanticRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Excerpt   pgtype.Text        `json:"excerpt"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ContextID pgtype.UUID        `json:"context_id"`
	Favorite  bool               `json:"favorite"`
	Archived  bool               `json:"archived"`
	Score     float64            `json:"score"`
}

func (q *Queries) SearchNotesSemantic(ctx context.Context, arg SearchNotesSemanticParams) ([]SearchNotesSemanticRow, error) {
	rows, err := q.db.Query(ctx, searchNotesSemantic, arg.Embedding, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesSemanticRow
	for rows.Next() {
		var i SearchNotesSemanticRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.UpdatedAt,
			&i.ContextID,
			&i.Favorite,
			&i.Archived,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
