// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNoteShare = `-- name: CreateNoteShare :one
INSERT INTO note_shares (note_id, user_id, permission)
VALUES ($1, $2, $3)
ON CONFLICT (note_id, user_id) DO UPDATE
SET permission = EXCLUDED.permission, updated_at = NOW()
RETURNING id, note_id, user_id, permission, created_at, updated_at
`

type CreateNoteShareParams struct {
	NoteID     pgtype.UUID `json:"note_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Permission string      `json:"permission"`
}

func (q *Queries) CreateNoteShare(ctx context.Context, arg CreateNoteShareParams) (NoteShare, error) {
	row := q.db.QueryRow(ctx, createNoteShare, arg.NoteID, arg.UserID, arg.Permission)
	var i NoteShare
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNoteShare = `-- name: DeleteNoteShare :exec
DELETE FROM note_shares
WHERE note_id = $1 AND user_id = $2
`

type DeleteNoteShareParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNoteShare(ctx context.Context, arg DeleteNoteShareParams) error {
	_, err := q.db.Exec(ctx, deleteNoteShare, arg.NoteID, arg.UserID)
	return err
}

const getNoteOwner = `-- name: GetNoteOwner :one
SELECT user_id FROM notes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNoteOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getNoteOwner, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getNoteShareForUser = `-- name: GetNoteShareForUser :one
SELECT id, note_id, user_id, permission, created_at, updated_at FROM note_shares
WHERE note_id = $1 AND user_id = $2
`

type GetNoteShareForUserParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetNoteShareForUser(ctx context.Context, arg GetNoteShareForUserParams) (NoteShare, error) {
	row := q.db.QueryRow(ctx, getNoteShareForUser, arg.NoteID, arg.UserID)
	var i NoteShare
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteShares = `-- name: GetNoteShares :many
SELECT ns.id, ns.note_id, ns.user_id, ns.permission, ns.created_at, ns.updated_at, u.email, u.name
FROM note_shares ns
JOIN users u ON u.id = ns.user_id
WHERE ns.note_id = $1
`

type GetNoteSharesRow struct {
	ID         pgtype.UUID        `json:"id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Permission string             `json:"permission"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
}

func (q *Queries) GetNoteShares(ctx context.Context, noteID pgtype.UUID) ([]GetNoteSharesRow, error) {
	rows, err := q.db.Query(ctx, getNoteShares, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNoteSharesRow
	for rows.Next() {
		var i GetNoteSharesRow
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
