// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_links.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableNoteShareLink = `-- name: DisableNoteShareLink :exec
UPDATE note_share_links
SET enabled = FALSE, updated_at = NOW()
WHERE note_id = $1
`

func (q *Queries) DisableNoteShareLink(ctx context.Context, noteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableNoteShareLink, noteID)
	return err
}

const getNoteShareLink = `-- name: GetNoteShareLink :one
SELECT note_id, token_id, enabled, created_at, updated_at
FROM note_share_links
WHERE note_id = $1
`

func (q *Queries) GetNoteShareLink(ctx context.Context, noteID pgtype.UUID) (NoteShareLink, error) {
	row := q.db.QueryRow(ctx, getNoteShareLink, noteID)
	var i NoteShareLink
	err := row.Scan(
		&i.NoteID,
		&i.TokenID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicNoteByShareToken = `-- name: GetPublicNoteByShareToken :one
SELECT n.id, n.document, n.updated_at
FROM notes n
JOIN note_share_links sl ON sl.note_id = n.id
WHERE sl.token_id = $1
  AND sl.enabled = TRUE
  AND n.deleted_at IS NULL
`

type GetPublicNoteByShareTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	Document  []byte             `json:"document"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublicNoteByShareToken(ctx context.Context, tokenID pgtype.UUID) (GetPublicNoteByShareTokenRow, error) {
	row := q.db.QueryRow(ctx, getPublicNoteByShareToken, tokenID)
	var i GetPublicNoteByShareTokenRow
	err := row.Scan(&i.ID, &i.Document, &i.UpdatedAt)
	return i, err
}

const upsertNoteShareLink = `-- name: UpsertNoteShareLink :one
INSERT INTO note_share_links (note_id, token_id, enabled)
VALUES ($1, $2, TRUE)
ON CONFLICT (note_id) DO UPDATE
SET token_id = EXCLUDED.token_id,
    enabled = TRUE,
    updated_at = NOW()
RETURNING note_id, token_id, enabled, created_at, updated_at
`

type UpsertNoteShareLinkParams struct {
	NoteID  pgtype.UUID `json:"note_id"`
	TokenID pgtype.UUID `json:"token_id"`
}

func (q *Queries) UpsertNoteShareLink(ctx context.Context, arg UpsertNoteShareLinkParams) (NoteShareLink, error) {
	row := q.db.QueryRow(ctx, upsertNoteShareLink, arg.NoteID, arg.TokenID)
	var i NoteShareLink
	err := row.Scan(
		&i.NoteID,
		&i.TokenID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
