// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared_link_ingestions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSharedLinkIngestion = `-- name: GetSharedLinkIngestion :one
SELECT user_id, share_id, note_id, operation_id, created_at
FROM shared_link_ingestions
WHERE user_id = $1 AND share_id = $2
`

type GetSharedLinkIngestionParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	ShareID pgtype.UUID `json:"share_id"`
}

func (q *Queries) GetSharedLinkIngestion(ctx context.Context, arg GetSharedLinkIngestionParams) (SharedLinkIngestion, error) {
	row := q.db.QueryRow(ctx, getSharedLinkIngestion, arg.UserID, arg.ShareID)
	var i SharedLinkIngestion
	err := row.Scan(
		&i.UserID,
		&i.ShareID,
		&i.NoteID,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const reserveSharedLinkIngestion = `-- name: ReserveSharedLinkIngestion :one
INSERT INTO shared_link_ingestions (user_id, share_id, note_id, operation_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, share_id) DO UPDATE
SET note_id = shared_link_ingestions.note_id
RETURNING user_id, share_id, note_id, operation_id, created_at
`

type ReserveSharedLinkIngestionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ShareID     pgtype.UUID `json:"share_id"`
	NoteID      pgtype.UUID `json:"note_id"`
	OperationID pgtype.UUID `json:"operation_id"`
}

func (q *Queries) ReserveSharedLinkIngestion(ctx context.Context, arg ReserveSharedLinkIngestionParams) (SharedLinkIngestion, error) {
	row := q.db.QueryRow(ctx, reserveSharedLinkIngestion,
		arg.UserID,
		arg.ShareID,
		arg.NoteID,
		arg.OperationID,
	)
	var i SharedLinkIngestion
	err := row.Scan(
		&i.UserID,
		&i.ShareID,
		&i.NoteID,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}
