// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncContexts = `-- name: GetSyncContexts :many
SELECT id, user_id, slug, name, created_at, updated_at FROM contexts
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncContextsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncContexts(ctx context.Context, arg GetSyncContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, getSyncContexts, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Context
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNotes = `-- name: GetSyncNotes :many
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status FROM notes
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncNotesParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncNotes(ctx context.Context, arg GetSyncNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getSyncNotes, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTags = `-- name: GetSyncTags :many
SELECT id, user_id, name, created_at FROM tags
WHERE user_id = $1
  AND (created_at > $2 OR $2::timestamptz IS NULL)
ORDER BY created_at ASC
LIMIT $3
`

type GetSyncTagsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTags(ctx context.Context, arg GetSyncTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getSyncTags, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTasks = `-- name: GetSyncTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncTasksParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTasks(ctx context.Context, arg GetSyncTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getSyncTasks, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteExpiredContexts = `-- name: HardDeleteExpiredContexts :exec
DELETE FROM contexts
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredContexts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredContexts)
	return err
}

const hardDeleteExpiredNotes = `-- name: HardDeleteExpiredNotes :exec
DELETE FROM notes
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredNotes)
	return err
}

const hardDeleteExpiredTasks = `-- name: HardDeleteExpiredTasks :exec
DELETE FROM tasks
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredTasks)
	return err
}

const upsertContext = `-- name: UpsertContext :one
INSERT INTO contexts (id, user_id, slug, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE
SET slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    updated_at = NOW()
WHERE contexts.user_id = EXCLUDED.user_id
RETURNING id, user_id, slug, name, created_at, updated_at
`

type UpsertContextParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertContext(ctx context.Context, arg UpsertContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, upsertContext,
		arg.ID,
		arg.UserID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNote = `-- name: UpsertNote :one
INSERT INTO notes (id, user_id, context_id, title, content, is_inbox, favorite, archived, embedding_status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), $11)
ON CONFLICT (id) DO UPDATE
SET context_id = EXCLUDED.context_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    is_inbox = EXCLUDED.is_inbox,
    favorite = EXCLUDED.favorite,
    archived = EXCLUDED.archived,
    embedding_status = EXCLUDED.embedding_status,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE notes.user_id = EXCLUDED.user_id
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status
`

type UpsertNoteParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Title           pgtype.Text        `json:"title"`
	Content         string             `json:"content"`
	IsInbox         bool               `json:"is_inbox"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
	EmbeddingStatus string             `json:"embedding_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, upsertNote,
		arg.ID,
		arg.UserID,
		arg.ContextID,
		arg.Title,
		arg.Content,
		arg.IsInbox,
		arg.Favorite,
		arg.Archived,
		arg.EmbeddingStatus,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
WHERE tags.user_id = EXCLUDED.user_id
RETURNING id, user_id, name, created_at
`

type UpsertTagParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (id, user_id, note_id, title, status, position, recurrence, due_date, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $10)
ON CONFLICT (id) DO UPDATE
SET note_id = EXCLUDED.note_id,
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    position = EXCLUDED.position,
    recurrence = EXCLUDED.recurrence,
    due_date = EXCLUDED.due_date,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE tasks.user_id = EXCLUDED.user_id
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at
`

type UpsertTaskParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Position   int32              `json:"position"`
	Recurrence pgtype.Text        `json:"recurrence"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.Title,
		arg.Status,
		arg.Position,
		arg.Recurrence,
		arg.DueDate,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertTaskCompletion = `-- name: UpsertTaskCompletion :exec
INSERT INTO task_completions (id, task_id, completed_at)
SELECT $1::uuid,
       $2::uuid,
       $3::timestamptz
FROM tasks
WHERE tasks.id = $2::uuid
  AND tasks.user_id = $4::uuid
ON CONFLICT (id) DO NOTHING
`

type UpsertTaskCompletionParams struct {
	ID          pgtype.UUID        `json:"id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UserID      pgtype.UUID        `json:"user_id"`
}

// Inserts a completion row only if the parent task belongs to the user
// (the SELECT returns 0 rows otherwise, making the INSERT a no-op).
// Completions are append-only history; existing rows are never updated.
func (q *Queries) UpsertTaskCompletion(ctx context.Context, arg UpsertTaskCompletionParams) error {
	_, err := q.db.Exec(ctx, upsertTaskCompletion,
		arg.ID,
		arg.TaskID,
		arg.CompletedAt,
		arg.UserID,
	)
	return err
}

// HAND-ADDED — not generated because sqlc is not on the CI PATH at time
// of writing. Run `sqlc generate` from backend/ to regenerate the full
// file; if the generated output matches then this comment can be removed.
const getSyncTaskCompletions = `-- name: GetSyncTaskCompletions :many
SELECT tc.id, tc.task_id, tc.completed_at, tc.due_date
FROM task_completions tc
JOIN tasks t ON t.id = tc.task_id
WHERE t.user_id = $1
  AND tc.completed_at > $2
ORDER BY tc.completed_at ASC
LIMIT $3
`

type GetSyncTaskCompletionsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

// Returns completion rows belonging to a user's tasks whose
// `completed_at` is newer than the cursor. The table has no
// `updated_at`, so we use `completed_at` as the pull cursor —
// completions are append-only, so any new completion is guaranteed
// to have a fresh timestamp. The join through `tasks` enforces the
// per-user scope since `task_completions` itself has no `user_id`.
func (q *Queries) GetSyncTaskCompletions(ctx context.Context, arg GetSyncTaskCompletionsParams) ([]TaskCompletion, error) {
	rows, err := q.db.Query(ctx, getSyncTaskCompletions, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCompletion
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CompletedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNoteTags = `-- name: GetSyncNoteTags :many
SELECT nt.note_id, nt.tag_id
FROM note_tags nt
JOIN notes n ON n.id = nt.note_id
WHERE n.user_id = $1
`

type GetSyncNoteTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSyncNoteTags(ctx context.Context, arg GetSyncNoteTagsParams) ([]NoteTag, error) {
	rows, err := q.db.Query(ctx, getSyncNoteTags, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteTag
	for rows.Next() {
		var i NoteTag
		if err := rows.Scan(
			&i.NoteID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNoteTag = `-- name: UpsertNoteTag :exec
INSERT INTO note_tags (note_id, tag_id)
SELECT $1::uuid, $2::uuid
WHERE EXISTS (
  SELECT 1 FROM notes WHERE id = $1::uuid AND user_id = $3::uuid
)
ON CONFLICT (note_id, tag_id) DO NOTHING
`

type UpsertNoteTagParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpsertNoteTag(ctx context.Context, arg UpsertNoteTagParams) error {
	_, err := q.db.Exec(ctx, upsertNoteTag, arg.NoteID, arg.TagID, arg.UserID)
	return err
}

const getSyncNoteLinks = `-- name: GetSyncNoteLinks :many
SELECT nl.id, nl.source_id, nl.target_id, nl.relation
FROM note_links nl
JOIN notes n ON n.id = nl.source_id
WHERE n.user_id = $1
`

type GetSyncNoteLinksParams struct {
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSyncNoteLinks(ctx context.Context, arg GetSyncNoteLinksParams) ([]NoteLink, error) {
	rows, err := q.db.Query(ctx, getSyncNoteLinks, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteLink
	for rows.Next() {
		var i NoteLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Relation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNoteLink = `-- name: UpsertNoteLink :exec
INSERT INTO note_links (id, source_id, target_id, relation)
SELECT $1::uuid,
       $2::uuid,
       $3::uuid,
       $4::varchar
WHERE EXISTS (
  SELECT 1 FROM notes WHERE id = $2::uuid AND user_id = $5::uuid
)
ON CONFLICT (id) DO UPDATE
SET relation = EXCLUDED.relation
`

type UpsertNoteLinkParams struct {
	ID       pgtype.UUID `json:"id"`
	SourceID pgtype.UUID `json:"source_id"`
	TargetID pgtype.UUID `json:"target_id"`
	Relation string      `json:"relation"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpsertNoteLink(ctx context.Context, arg UpsertNoteLinkParams) error {
	_, err := q.db.Exec(ctx, upsertNoteLink, arg.ID, arg.SourceID, arg.TargetID, arg.Relation, arg.UserID)
	return err
}
