// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncContexts = `-- name: GetSyncContexts :many
SELECT id, user_id, slug, name, created_at, updated_at FROM contexts
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncContextsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncContexts(ctx context.Context, arg GetSyncContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, getSyncContexts, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Context
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNotes = `-- name: GetSyncNotes :many
SELECT id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status FROM notes
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncNotesParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncNotes(ctx context.Context, arg GetSyncNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, getSyncNotes, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTags = `-- name: GetSyncTags :many
SELECT id, user_id, name, created_at FROM tags
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type GetSyncTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetSyncTags(ctx context.Context, arg GetSyncTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getSyncTags, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTasks = `-- name: GetSyncTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncTasksParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTasks(ctx context.Context, arg GetSyncTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getSyncTasks, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContext = `-- name: UpsertContext :one
INSERT INTO contexts (id, user_id, slug, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE
SET slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    updated_at = NOW()
WHERE contexts.user_id = EXCLUDED.user_id
RETURNING id, user_id, slug, name, created_at, updated_at
`

type UpsertContextParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertContext(ctx context.Context, arg UpsertContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, upsertContext,
		arg.ID,
		arg.UserID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNote = `-- name: UpsertNote :one
INSERT INTO notes (id, user_id, context_id, title, content, is_inbox, favorite, archived, embedding_status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), $11)
ON CONFLICT (id) DO UPDATE
SET context_id = EXCLUDED.context_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    is_inbox = EXCLUDED.is_inbox,
    favorite = EXCLUDED.favorite,
    archived = EXCLUDED.archived,
    embedding_status = EXCLUDED.embedding_status,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE notes.user_id = EXCLUDED.user_id
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status
`

type UpsertNoteParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Title           pgtype.Text        `json:"title"`
	Content         string             `json:"content"`
	IsInbox         bool               `json:"is_inbox"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
	EmbeddingStatus string             `json:"embedding_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, upsertNote,
		arg.ID,
		arg.UserID,
		arg.ContextID,
		arg.Title,
		arg.Content,
		arg.IsInbox,
		arg.Favorite,
		arg.Archived,
		arg.EmbeddingStatus,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
WHERE tags.user_id = EXCLUDED.user_id
RETURNING id, user_id, name, created_at
`

type UpsertTagParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (id, user_id, note_id, title, status, position, recurrence, due_date, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $10)
ON CONFLICT (id) DO UPDATE
SET note_id = EXCLUDED.note_id,
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    position = EXCLUDED.position,
    recurrence = EXCLUDED.recurrence,
    due_date = EXCLUDED.due_date,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE tasks.user_id = EXCLUDED.user_id
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at
`

type UpsertTaskParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Position   int32              `json:"position"`
	Recurrence pgtype.Text        `json:"recurrence"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.Title,
		arg.Status,
		arg.Position,
		arg.Recurrence,
		arg.DueDate,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
