// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncContexts = `-- name: GetSyncContexts :many
SELECT id, user_id, slug, name, created_at, updated_at FROM contexts
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetSyncContextsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncContexts(ctx context.Context, arg GetSyncContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, getSyncContexts, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Context
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNoteLinks = `-- name: GetSyncNoteLinks :many
SELECT nl.source_id, nl.target_id, nl.relation, nl.id, nl.created_at, nl.updated_at
FROM note_links nl
JOIN notes n ON n.id = nl.source_id
LEFT JOIN note_shares ns ON ns.note_id = n.id AND ns.user_id = $1::uuid
WHERE (n.user_id = $1::uuid OR ns.user_id = $1::uuid)
`

func (q *Queries) GetSyncNoteLinks(ctx context.Context, userID pgtype.UUID) ([]NoteLink, error) {
	rows, err := q.db.Query(ctx, getSyncNoteLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteLink
	for rows.Next() {
		var i NoteLink
		if err := rows.Scan(
			&i.SourceID,
			&i.TargetID,
			&i.Relation,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNoteTags = `-- name: GetSyncNoteTags :many
SELECT nt.note_id, nt.tag_id
FROM note_tags nt
JOIN notes n ON n.id = nt.note_id
LEFT JOIN note_shares ns ON ns.note_id = n.id AND ns.user_id = $1::uuid
WHERE (n.user_id = $1::uuid OR ns.user_id = $1::uuid)
`

func (q *Queries) GetSyncNoteTags(ctx context.Context, userID pgtype.UUID) ([]NoteTag, error) {
	rows, err := q.db.Query(ctx, getSyncNoteTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteTag
	for rows.Next() {
		var i NoteTag
		if err := rows.Scan(&i.NoteID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncNotes = `-- name: GetSyncNotes :many
SELECT n.id, n.user_id, n.context_id, n.title, n.content, n.excerpt, n.is_inbox, n.favorite, n.archived, n.search_vector, n.created_at, n.updated_at, n.deleted_at, n.embedding_status, n.hide_completed,
  COALESCE(ns.permission, '')::text AS shared_permission,
  COALESCE(u.email, '')::text AS shared_by_email,
  COALESCE(u.name, '')::text AS shared_by_name
FROM notes n
LEFT JOIN note_shares ns ON ns.note_id = n.id AND ns.user_id = $1::uuid
LEFT JOIN users u ON u.id = n.user_id
WHERE (n.user_id = $1::uuid OR ns.user_id = $1::uuid)
  AND n.updated_at > $2
ORDER BY n.updated_at ASC
LIMIT $3
`

type GetSyncNotesParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

type GetSyncNotesRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ContextID        pgtype.UUID        `json:"context_id"`
	Title            pgtype.Text        `json:"title"`
	Content          string             `json:"content"`
	Excerpt          pgtype.Text        `json:"excerpt"`
	IsInbox          bool               `json:"is_inbox"`
	Favorite         bool               `json:"favorite"`
	Archived         bool               `json:"archived"`
	SearchVector     pgtype.Text        `json:"search_vector"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	EmbeddingStatus  string             `json:"embedding_status"`
	HideCompleted    bool               `json:"hide_completed"`
	SharedPermission string             `json:"shared_permission"`
	SharedByEmail    string             `json:"shared_by_email"`
	SharedByName     string             `json:"shared_by_name"`
}

func (q *Queries) GetSyncNotes(ctx context.Context, arg GetSyncNotesParams) ([]GetSyncNotesRow, error) {
	rows, err := q.db.Query(ctx, getSyncNotes, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSyncNotesRow
	for rows.Next() {
		var i GetSyncNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContextID,
			&i.Title,
			&i.Content,
			&i.Excerpt,
			&i.IsInbox,
			&i.Favorite,
			&i.Archived,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmbeddingStatus,
			&i.HideCompleted,
			&i.SharedPermission,
			&i.SharedByEmail,
			&i.SharedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTags = `-- name: GetSyncTags :many
SELECT id, user_id, name, created_at FROM tags
WHERE user_id = $1
  AND (created_at > $2 OR $2::timestamptz IS NULL)
ORDER BY created_at ASC
LIMIT $3
`

type GetSyncTagsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTags(ctx context.Context, arg GetSyncTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getSyncTags, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTaskCompletions = `-- name: GetSyncTaskCompletions :many
SELECT tc.id, tc.task_id, tc.completed_at, tc.due_date
FROM task_completions tc
JOIN tasks t ON t.id = tc.task_id
JOIN notes n ON n.id = t.note_id
LEFT JOIN note_shares ns ON ns.note_id = n.id AND ns.user_id = $1::uuid
WHERE (n.user_id = $1::uuid OR ns.user_id = $1::uuid)
  AND tc.completed_at > $2
ORDER BY tc.completed_at ASC
LIMIT $3
`

type GetSyncTaskCompletionsParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTaskCompletions(ctx context.Context, arg GetSyncTaskCompletionsParams) ([]TaskCompletion, error) {
	rows, err := q.db.Query(ctx, getSyncTaskCompletions, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCompletion
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CompletedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncTasks = `-- name: GetSyncTasks :many
SELECT t.id, t.note_id, t.user_id, t.title, t.status, t.due_date, t.recurrence, t.position, t.created_at, t.updated_at, t.deleted_at, t.completed_at
FROM tasks t
JOIN notes n ON n.id = t.note_id
LEFT JOIN note_shares ns ON ns.note_id = n.id AND ns.user_id = $1::uuid
WHERE (n.user_id = $1::uuid OR ns.user_id = $1::uuid)
  AND t.updated_at > $2
ORDER BY t.updated_at ASC
LIMIT $3
`

type GetSyncTasksParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Limit        int32              `json:"limit"`
}

func (q *Queries) GetSyncTasks(ctx context.Context, arg GetSyncTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getSyncTasks, arg.UserID, arg.LastSyncedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteExpiredContexts = `-- name: HardDeleteExpiredContexts :exec
DELETE FROM contexts
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredContexts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredContexts)
	return err
}

const hardDeleteExpiredNotes = `-- name: HardDeleteExpiredNotes :exec
DELETE FROM notes
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredNotes)
	return err
}

const hardDeleteExpiredTasks = `-- name: HardDeleteExpiredTasks :exec
DELETE FROM tasks
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) HardDeleteExpiredTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteExpiredTasks)
	return err
}

const upsertContext = `-- name: UpsertContext :one
INSERT INTO contexts (id, user_id, slug, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE
SET slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    updated_at = NOW()
WHERE contexts.user_id = EXCLUDED.user_id
RETURNING id, user_id, slug, name, created_at, updated_at
`

type UpsertContextParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertContext(ctx context.Context, arg UpsertContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, upsertContext,
		arg.ID,
		arg.UserID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNote = `-- name: UpsertNote :one
INSERT INTO notes (id, user_id, context_id, title, content, is_inbox, favorite, archived, embedding_status, hide_completed, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), $12)
ON CONFLICT (id) DO UPDATE
SET context_id = EXCLUDED.context_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    is_inbox = EXCLUDED.is_inbox,
    favorite = EXCLUDED.favorite,
    archived = EXCLUDED.archived,
    embedding_status = EXCLUDED.embedding_status,
    hide_completed = EXCLUDED.hide_completed,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE notes.user_id = EXCLUDED.user_id
RETURNING id, user_id, context_id, title, content, excerpt, is_inbox, favorite, archived, search_vector, created_at, updated_at, deleted_at, embedding_status, hide_completed
`

type UpsertNoteParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContextID       pgtype.UUID        `json:"context_id"`
	Title           pgtype.Text        `json:"title"`
	Content         string             `json:"content"`
	IsInbox         bool               `json:"is_inbox"`
	Favorite        bool               `json:"favorite"`
	Archived        bool               `json:"archived"`
	EmbeddingStatus string             `json:"embedding_status"`
	HideCompleted   bool               `json:"hide_completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, upsertNote,
		arg.ID,
		arg.UserID,
		arg.ContextID,
		arg.Title,
		arg.Content,
		arg.IsInbox,
		arg.Favorite,
		arg.Archived,
		arg.EmbeddingStatus,
		arg.HideCompleted,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContextID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.IsInbox,
		&i.Favorite,
		&i.Archived,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EmbeddingStatus,
		&i.HideCompleted,
	)
	return i, err
}

const upsertNoteLink = `-- name: UpsertNoteLink :exec
INSERT INTO note_links (id, source_id, target_id, relation, created_at, updated_at)
SELECT $1::uuid,
       $2::uuid,
       $3::uuid,
       $4::varchar,
       $5::timestamptz,
       NOW()
WHERE EXISTS (
  SELECT 1 FROM notes WHERE id = $2::uuid
    AND (user_id = $6::uuid
         OR EXISTS (SELECT 1 FROM note_shares
                    WHERE note_id = $2::uuid
                      AND user_id = $6::uuid
                      AND permission = 'edit'))
)
ON CONFLICT (id) DO UPDATE
SET relation = EXCLUDED.relation,
    updated_at = NOW()
`

type UpsertNoteLinkParams struct {
	ID        pgtype.UUID        `json:"id"`
	SourceID  pgtype.UUID        `json:"source_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Relation  string             `json:"relation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertNoteLink(ctx context.Context, arg UpsertNoteLinkParams) error {
	_, err := q.db.Exec(ctx, upsertNoteLink,
		arg.ID,
		arg.SourceID,
		arg.TargetID,
		arg.Relation,
		arg.CreatedAt,
		arg.UserID,
	)
	return err
}

const upsertNoteTag = `-- name: UpsertNoteTag :exec
INSERT INTO note_tags (note_id, tag_id)
SELECT $1::uuid, $2::uuid
WHERE EXISTS (
  SELECT 1 FROM notes WHERE id = $1::uuid
    AND (user_id = $3::uuid
         OR EXISTS (SELECT 1 FROM note_shares
                    WHERE note_id = $1::uuid
                      AND user_id = $3::uuid
                      AND permission = 'edit'))
)
ON CONFLICT (note_id, tag_id) DO NOTHING
`

type UpsertNoteTagParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	TagID  pgtype.UUID `json:"tag_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpsertNoteTag(ctx context.Context, arg UpsertNoteTagParams) error {
	_, err := q.db.Exec(ctx, upsertNoteTag, arg.NoteID, arg.TagID, arg.UserID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
WHERE tags.user_id = EXCLUDED.user_id
RETURNING id, user_id, name, created_at
`

type UpsertTagParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (id, user_id, note_id, title, status, position, recurrence, due_date, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $10)
ON CONFLICT (id) DO UPDATE
SET note_id = EXCLUDED.note_id,
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    position = EXCLUDED.position,
    recurrence = EXCLUDED.recurrence,
    due_date = EXCLUDED.due_date,
    updated_at = NOW(),
    deleted_at = EXCLUDED.deleted_at
WHERE tasks.user_id = EXCLUDED.user_id
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at
`

type UpsertTaskParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	NoteID     pgtype.UUID        `json:"note_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Position   int32              `json:"position"`
	Recurrence pgtype.Text        `json:"recurrence"`
	DueDate    pgtype.Date        `json:"due_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.ID,
		arg.UserID,
		arg.NoteID,
		arg.Title,
		arg.Status,
		arg.Position,
		arg.Recurrence,
		arg.DueDate,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CompletedAt,
	)
	return i, err
}

const upsertTaskCompletion = `-- name: UpsertTaskCompletion :exec
INSERT INTO task_completions (id, task_id, completed_at, status)
SELECT $1::uuid,
       $2::uuid,
       $3::timestamptz,
       'completed'
FROM tasks
WHERE tasks.id = $2::uuid
  AND (tasks.user_id = $4::uuid
       OR EXISTS (SELECT 1 FROM note_shares ns
                  WHERE ns.note_id = tasks.note_id
                    AND ns.user_id = $4::uuid
                    AND ns.permission = 'edit'))
ON CONFLICT (id) DO NOTHING
`

type UpsertTaskCompletionParams struct {
	ID          pgtype.UUID        `json:"id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertTaskCompletion(ctx context.Context, arg UpsertTaskCompletionParams) error {
	_, err := q.db.Exec(ctx, upsertTaskCompletion,
		arg.ID,
		arg.TaskID,
		arg.CompletedAt,
		arg.UserID,
	)
	return err
}
