// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedTasks = `-- name: CountCompletedTasks :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1 AND deleted_at IS NULL AND status = 'done'
`

func (q *Queries) CountCompletedTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenTasks = `-- name: CountOpenTasks :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1 AND deleted_at IS NULL AND status = 'open'
`

func (q *Queries) CountOpenTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (note_id, user_id, title, due_date, recurrence, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at
`

type CreateTaskParams struct {
	NoteID     pgtype.UUID `json:"note_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Title      string      `json:"title"`
	DueDate    pgtype.Date `json:"due_date"`
	Recurrence pgtype.Text `json:"recurrence"`
	Position   string      `json:"position"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.NoteID,
		arg.UserID,
		arg.Title,
		arg.DueDate,
		arg.Recurrence,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createTaskCompletion = `-- name: CreateTaskCompletion :one
INSERT INTO task_completions (task_id, completed_at, scheduled_at, due_date)
VALUES ($1, NOW(), NOW(), $2)
RETURNING id, task_id, completed_at, scheduled_at, due_date
`

type CreateTaskCompletionParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	DueDate pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateTaskCompletion(ctx context.Context, arg CreateTaskCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRow(ctx, createTaskCompletion, arg.TaskID, arg.DueDate)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CompletedAt,
		&i.ScheduledAt,
		&i.DueDate,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const deleteTaskByNodeID = `-- name: DeleteTaskByNodeID :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteTaskByNodeIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTaskByNodeID(ctx context.Context, arg DeleteTaskByNodeIDParams) error {
	_, err := q.db.Exec(ctx, deleteTaskByNodeID, arg.ID, arg.UserID)
	return err
}

const deleteTasksByNoteID = `-- name: DeleteTasksByNoteID :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE note_id = $1 AND deleted_at IS NULL AND id <> ALL($2::uuid[])
`

type DeleteTasksByNoteIDParams struct {
	NoteID  pgtype.UUID   `json:"note_id"`
	KeepIds []pgtype.UUID `json:"keep_ids"`
}

func (q *Queries) DeleteTasksByNoteID(ctx context.Context, arg DeleteTasksByNoteIDParams) error {
	_, err := q.db.Exec(ctx, deleteTasksByNoteID, arg.NoteID, arg.KeepIds)
	return err
}

const getRecentlyCompletedTasks = `-- name: GetRecentlyCompletedTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = 'done'
  AND completed_at >= NOW() - ($2::int || ' days')::interval
ORDER BY completed_at DESC
`

type GetRecentlyCompletedTasksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Days   int32       `json:"days"`
}

func (q *Queries) GetRecentlyCompletedTasks(ctx context.Context, arg GetRecentlyCompletedTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getRecentlyCompletedTasks, arg.UserID, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR note_id = $4)
  AND ($5::varchar IS NULL OR status = $5)
  AND ($6::date IS NULL OR due_date >= $6::date)
  AND ($7::date IS NULL OR due_date <= $7::date)
ORDER BY due_date ASC NULLS LAST, position ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type GetTasksParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	NoteID    pgtype.UUID `json:"note_id"`
	Status    pgtype.Text `json:"status"`
	DueAfter  pgtype.Date `json:"due_after"`
	DueBefore pgtype.Date `json:"due_before"`
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.NoteID,
		arg.Status,
		arg.DueAfter,
		arg.DueBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByNodeID = `-- name: GetTasksByNodeID :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE id = $1 AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetTasksByNodeID(ctx context.Context, id pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByNodeID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByNoteID = `-- name: GetTasksByNoteID :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE user_id = $1 AND note_id = $2 AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

type GetTasksByNoteIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	NoteID pgtype.UUID `json:"note_id"`
}

func (q *Queries) GetTasksByNoteID(ctx context.Context, arg GetTasksByNoteIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByNoteID, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayTasks = `-- name: GetTodayTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = 'open'
  AND due_date IS NOT NULL
  AND due_date <= $2::date
ORDER BY due_date ASC, position ASC, created_at ASC
`

type GetTodayTasksParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) GetTodayTasks(ctx context.Context, arg GetTodayTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTodayTasks, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND title ILIKE '%' || $4::text || '%'
  AND ($5::varchar IS NULL OR status = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchTasksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Query  string      `json:"query"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, searchTasks,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Query,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title        = CASE WHEN $3::bool        THEN $4        ELSE title        END,
    status       = CASE WHEN $5::bool       THEN $6       ELSE status       END,
    due_date     = CASE WHEN $7::bool     THEN $8     ELSE due_date     END,
    recurrence   = CASE WHEN $9::bool   THEN $10   ELSE recurrence   END,
    position     = CASE WHEN $11::bool     THEN $12     ELSE position     END,
    completed_at = CASE WHEN $13::bool THEN $14 ELSE completed_at END,
    updated_at   = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at, completed_at
`

type UpdateTaskParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	SetTitle       pgtype.Bool        `json:"set_title"`
	Title          pgtype.Text        `json:"title"`
	SetStatus      pgtype.Bool        `json:"set_status"`
	Status         pgtype.Text        `json:"status"`
	SetDueDate     pgtype.Bool        `json:"set_due_date"`
	DueDate        pgtype.Date        `json:"due_date"`
	SetRecurrence  pgtype.Bool        `json:"set_recurrence"`
	Recurrence     pgtype.Text        `json:"recurrence"`
	SetPosition    pgtype.Bool        `json:"set_position"`
	Position       pgtype.Text        `json:"position"`
	SetCompletedAt pgtype.Bool        `json:"set_completed_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.SetTitle,
		arg.Title,
		arg.SetStatus,
		arg.Status,
		arg.SetDueDate,
		arg.DueDate,
		arg.SetRecurrence,
		arg.Recurrence,
		arg.SetPosition,
		arg.Position,
		arg.SetCompletedAt,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CompletedAt,
	)
	return i, err
}

const upsertTasksBatch = `-- name: UpsertTasksBatch :exec
INSERT INTO tasks (id, note_id, user_id, title, status, due_date, recurrence, position, completed_at, created_at, deleted_at)
SELECT
  unnest($1::uuid[]),
  unnest($2::uuid[]),
  unnest($3::uuid[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::date[]),
  unnest($7::text[]),
  unnest($8::text[]),
  unnest($9::timestamptz[]),
  unnest($10::timestamptz[]),
  unnest($11::timestamptz[])
ON CONFLICT (id) DO UPDATE SET
  title        = EXCLUDED.title,
  status       = EXCLUDED.status,
  due_date     = EXCLUDED.due_date,
  recurrence   = EXCLUDED.recurrence,
  position     = EXCLUDED.position,
  completed_at = EXCLUDED.completed_at,
  deleted_at   = EXCLUDED.deleted_at,
  updated_at   = NOW()
`

type UpsertTasksBatchParams struct {
	Column1  []pgtype.UUID        `json:"column_1"`
	Column2  []pgtype.UUID        `json:"column_2"`
	Column3  []pgtype.UUID        `json:"column_3"`
	Column4  []string             `json:"column_4"`
	Column5  []string             `json:"column_5"`
	Column6  []pgtype.Date        `json:"column_6"`
	Column7  []string             `json:"column_7"`
	Column8  []string             `json:"column_8"`
	Column9  []pgtype.Timestamptz `json:"column_9"`
	Column10 []pgtype.Timestamptz `json:"column_10"`
	Column11 []pgtype.Timestamptz `json:"column_11"`
}

func (q *Queries) UpsertTasksBatch(ctx context.Context, arg UpsertTasksBatchParams) error {
	_, err := q.db.Exec(ctx, upsertTasksBatch,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
	)
	return err
}
