// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (note_id, user_id, title, due_date, recurrence, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	NoteID     pgtype.UUID        `json:"note_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      string             `json:"title"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	Recurrence pgtype.Text        `json:"recurrence"`
	Position   int32              `json:"position"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.NoteID,
		arg.UserID,
		arg.Title,
		arg.DueDate,
		arg.Recurrence,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskCompletion = `-- name: CreateTaskCompletion :one
INSERT INTO task_completions (task_id, status)
VALUES ($1, $2)
RETURNING id, task_id, completed_at, status
`

type CreateTaskCompletionParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Status string      `json:"status"`
}

func (q *Queries) CreateTaskCompletion(ctx context.Context, arg CreateTaskCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRow(ctx, createTaskCompletion, arg.TaskID, arg.Status)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CompletedAt,
		&i.Status,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR note_id = $4)
  AND ($5::varchar IS NULL OR status = $5)
  AND ($6::timestamptz IS NULL OR due_date >= $6)
  AND ($7::timestamptz IS NULL OR due_date <= $7)
ORDER BY due_date ASC NULLS LAST, position ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type GetTasksParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	NoteID    pgtype.UUID        `json:"note_id"`
	Status    pgtype.Text        `json:"status"`
	DueAfter  pgtype.Timestamptz `json:"due_after"`
	DueBefore pgtype.Timestamptz `json:"due_before"`
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.NoteID,
		arg.Status,
		arg.DueAfter,
		arg.DueBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByNoteID = `-- name: GetTasksByNoteID :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE user_id = $1 AND note_id = $2 AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

type GetTasksByNoteIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	NoteID pgtype.UUID `json:"note_id"`
}

func (q *Queries) GetTasksByNoteID(ctx context.Context, arg GetTasksByNoteIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByNoteID, arg.UserID, arg.NoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayTasks = `-- name: GetTodayTasks :many
SELECT id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = 'open'
  AND due_date IS NOT NULL
  AND due_date <= $2::timestamptz
ORDER BY due_date ASC, position ASC, created_at ASC
`

type GetTodayTasksParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

func (q *Queries) GetTodayTasks(ctx context.Context, arg GetTodayTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTodayTasks, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.Recurrence,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($3, title),
    status = COALESCE($4, status),
    due_date = COALESCE($5, due_date),
    recurrence = COALESCE($6, recurrence),
    position = COALESCE($7, position),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, note_id, user_id, title, status, due_date, recurrence, position, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Title      pgtype.Text        `json:"title"`
	Status     pgtype.Text        `json:"status"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	Recurrence pgtype.Text        `json:"recurrence"`
	Position   pgtype.Int4        `json:"position"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.DueDate,
		arg.Recurrence,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.Recurrence,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
