// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskForOwner = `-- name: GetTaskForOwner :one
SELECT id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
       completions, completion_history, is_completed, last_completed_at, revision, schedule_generation,
       created_at, updated_at, deleted_at
FROM tasks
WHERE id = $1 AND owner_user_id = $2
`

type GetTaskForOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetTaskForOwner(ctx context.Context, arg GetTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.DueDate,
		&i.HasTime,
		&i.RecurrenceRule,
		&i.Reminder,
		&i.Completions,
		&i.CompletionHistory,
		&i.IsCompleted,
		&i.LastCompletedAt,
		&i.Revision,
		&i.ScheduleGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskOperation = `-- name: GetTaskOperation :one
SELECT task_id, operation_id, payload_hash, response_json, created_at
FROM task_operations
WHERE task_id = $1 AND operation_id = $2
`

type GetTaskOperationParams struct {
	TaskID      pgtype.UUID `json:"task_id"`
	OperationID pgtype.UUID `json:"operation_id"`
}

func (q *Queries) GetTaskOperation(ctx context.Context, arg GetTaskOperationParams) (TaskOperation, error) {
	row := q.db.QueryRow(ctx, getTaskOperation, arg.TaskID, arg.OperationID)
	var i TaskOperation
	err := row.Scan(
		&i.TaskID,
		&i.OperationID,
		&i.PayloadHash,
		&i.ResponseJson,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskWatermark = `-- name: GetTaskWatermark :one
SELECT COALESCE(MAX(sequence), 0)::bigint
FROM sync_changes
WHERE target_user_id = $1
`

func (q *Queries) GetTaskWatermark(ctx context.Context, targetUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTaskWatermark, targetUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
                   completions, completion_history, is_completed, last_completed_at, revision, schedule_generation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 1, $12)
ON CONFLICT (id) DO NOTHING
RETURNING id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
          completions, completion_history, is_completed, last_completed_at, revision, schedule_generation,
          created_at, updated_at, deleted_at
`

type InsertTaskParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Title              string             `json:"title"`
	DueDate            pgtype.Timestamp   `json:"due_date"`
	HasTime            bool               `json:"has_time"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	Reminder           pgtype.Text        `json:"reminder"`
	Completions        []byte             `json:"completions"`
	CompletionHistory  []byte             `json:"completion_history"`
	IsCompleted        bool               `json:"is_completed"`
	LastCompletedAt    pgtype.Timestamptz `json:"last_completed_at"`
	ScheduleGeneration int64              `json:"schedule_generation"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.OwnerUserID,
		arg.Title,
		arg.DueDate,
		arg.HasTime,
		arg.RecurrenceRule,
		arg.Reminder,
		arg.Completions,
		arg.CompletionHistory,
		arg.IsCompleted,
		arg.LastCompletedAt,
		arg.ScheduleGeneration,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.DueDate,
		&i.HasTime,
		&i.RecurrenceRule,
		&i.Reminder,
		&i.Completions,
		&i.CompletionHistory,
		&i.IsCompleted,
		&i.LastCompletedAt,
		&i.Revision,
		&i.ScheduleGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTaskOperation = `-- name: InsertTaskOperation :exec
INSERT INTO task_operations (task_id, operation_id, payload_hash, response_json)
VALUES ($1, $2, $3, $4)
`

type InsertTaskOperationParams struct {
	TaskID       pgtype.UUID `json:"task_id"`
	OperationID  pgtype.UUID `json:"operation_id"`
	PayloadHash  string      `json:"payload_hash"`
	ResponseJson []byte      `json:"response_json"`
}

func (q *Queries) InsertTaskOperation(ctx context.Context, arg InsertTaskOperationParams) error {
	_, err := q.db.Exec(ctx, insertTaskOperation,
		arg.TaskID,
		arg.OperationID,
		arg.PayloadHash,
		arg.ResponseJson,
	)
	return err
}

const insertTaskSyncChange = `-- name: InsertTaskSyncChange :exec
INSERT INTO sync_changes (target_user_id, kind, task_id, revision)
VALUES ($1, $2, $3, $4)
`

type InsertTaskSyncChangeParams struct {
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Kind         string      `json:"kind"`
	TaskID       pgtype.UUID `json:"task_id"`
	Revision     pgtype.Int8 `json:"revision"`
}

func (q *Queries) InsertTaskSyncChange(ctx context.Context, arg InsertTaskSyncChangeParams) error {
	_, err := q.db.Exec(ctx, insertTaskSyncChange,
		arg.TargetUserID,
		arg.Kind,
		arg.TaskID,
		arg.Revision,
	)
	return err
}

const listTasksForBootstrap = `-- name: ListTasksForBootstrap :many
SELECT id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
       completions, completion_history, is_completed, last_completed_at, revision, schedule_generation,
       created_at, updated_at, deleted_at
FROM tasks
WHERE owner_user_id = $1
ORDER BY due_date NULLS LAST, id
`

func (q *Queries) ListTasksForBootstrap(ctx context.Context, ownerUserID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksForBootstrap, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.DueDate,
			&i.HasTime,
			&i.RecurrenceRule,
			&i.Reminder,
			&i.Completions,
			&i.CompletionHistory,
			&i.IsCompleted,
			&i.LastCompletedAt,
			&i.Revision,
			&i.ScheduleGeneration,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForOwner = `-- name: LockTaskForOwner :one
SELECT id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
       completions, completion_history, is_completed, last_completed_at, revision, schedule_generation,
       created_at, updated_at, deleted_at
FROM tasks
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type LockTaskForOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) LockTaskForOwner(ctx context.Context, arg LockTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, lockTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.DueDate,
		&i.HasTime,
		&i.RecurrenceRule,
		&i.Reminder,
		&i.Completions,
		&i.CompletionHistory,
		&i.IsCompleted,
		&i.LastCompletedAt,
		&i.Revision,
		&i.ScheduleGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3, due_date = $4, has_time = $5, recurrence_rule = $6, reminder = $7,
    completions = $8, completion_history = $9, is_completed = $10, last_completed_at = $11,
    revision = revision + 1, schedule_generation = $12,
    deleted_at = $13
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, title, due_date, has_time, recurrence_rule, reminder,
          completions, completion_history, is_completed, last_completed_at, revision, schedule_generation,
          created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Title              string             `json:"title"`
	DueDate            pgtype.Timestamp   `json:"due_date"`
	HasTime            bool               `json:"has_time"`
	RecurrenceRule     pgtype.Text        `json:"recurrence_rule"`
	Reminder           pgtype.Text        `json:"reminder"`
	Completions        []byte             `json:"completions"`
	CompletionHistory  []byte             `json:"completion_history"`
	IsCompleted        bool               `json:"is_completed"`
	LastCompletedAt    pgtype.Timestamptz `json:"last_completed_at"`
	ScheduleGeneration int64              `json:"schedule_generation"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OwnerUserID,
		arg.Title,
		arg.DueDate,
		arg.HasTime,
		arg.RecurrenceRule,
		arg.Reminder,
		arg.Completions,
		arg.CompletionHistory,
		arg.IsCompleted,
		arg.LastCompletedAt,
		arg.ScheduleGeneration,
		arg.DeletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.DueDate,
		&i.HasTime,
		&i.RecurrenceRule,
		&i.Reminder,
		&i.Completions,
		&i.CompletionHistory,
		&i.IsCompleted,
		&i.LastCompletedAt,
		&i.Revision,
		&i.ScheduleGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
