import 'dart:math';
import 'package:flutter_test/flutter_test.dart';
import 'package:crdt_lf/crdt_lf.dart';

void main() {
  test('crdt_lf fuzzing convergence under shuffled and duplicated delivery', () {
    const seedEnv = String.fromEnvironment('FUZZ_SEED');
    final seed = seedEnv.isNotEmpty ? int.parse(seedEnv) : DateTime.now().millisecondsSinceEpoch;
    final rand = Random(seed);
    print('[Fuzz] Running with seed: $seed');

    for (var iteration = 0; iteration < 1000; iteration++) {
      final base = "O rato roeu a roupa do rei de Roma.";
      
      // Initialize base text on one document
      final initPeerId = PeerId.parse('00000000-0000-4000-8000-000000000009');
      final initDoc = CRDTDocument(peerId: initPeerId)..registerDefaultFactories();
      final initHandler = CRDTFugueTextHandler(initDoc, 'text-fuzz');
      initHandler.insert(0, base);
      final initChanges = initDoc.exportChanges();

      // Setup 4 client docs and import base changes
      final docs = List.generate(4, (i) {
        final peerId = PeerId.parse('00000000-0000-4000-8000-00000000000${i}');
        final doc = CRDTDocument(peerId: peerId)..registerDefaultFactories();
        // Initialize a Fugue text handler on each doc
        final handler = CRDTFugueTextHandler(doc, 'text-fuzz');
        doc.importChanges(initChanges);
        return doc;
      });

      // Track baseline version vector after base initialization
      final baselines = docs.map((d) => d.getVersionVector()).toList();

      // Run local concurrent operations on each doc
      final List<Change> allChanges = [];
      for (var i = 0; i < docs.length; i++) {
        final doc = docs[i];
        final textHandler = doc.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        
        final opCount = rand.nextInt(5) + 1;
        for (var j = 0; j < opCount; j++) {
          // Pick random position to insert or delete
          final currentLen = textHandler.value.length;
          if (currentLen > 0 && rand.nextBool()) {
            // Delete
            final pos = rand.nextInt(currentLen);
            final count = rand.nextInt(min(5, currentLen - pos)) + 1;
            textHandler.delete(pos, count);
          } else {
            // Insert
            final pos = rand.nextInt(currentLen + 1);
            final text = String.fromCharCodes(
              List.generate(rand.nextInt(5) + 1, (_) => rand.nextInt(26) + 97)
            );
            textHandler.insert(pos, text);
          }
        }
        // Export changes generated by this client since the baseline
        allChanges.addAll(doc.exportChanges(fromVersionVector: baselines[i]));
      }

      // Simulate network delivery: shuffle changes
      allChanges.shuffle(rand);

      // Apply changes to each document in different orders (shuffled per document)
      for (final doc in docs) {
        final docChanges = List<Change>.from(allChanges)..shuffle(rand);
        // Duplicate changes to simulate at-least-once delivery (idempotency check)
        final duplicatedChanges = <Change>[];
        for (final change in docChanges) {
          duplicatedChanges.add(change);
          duplicatedChanges.add(change);
        }

        // Apply changes one by one. Since delivery is shuffled, some changes
        // might arrive before their dependencies and be skipped. We retry
        // applying pending changes until all are successfully imported.
        var pending = List<Change>.from(duplicatedChanges);
        while (pending.isNotEmpty) {
          final beforeCount = pending.length;
          final nextPending = <Change>[];
          for (final change in pending) {
            final applied = doc.importChanges([change]);
            if (applied == 0) {
              final vv = doc.getVersionVector();
              final clock = vv[change.author];
              final alreadyHas = clock != null && change.hlc.compareTo(clock) <= 0;
              if (!alreadyHas) {
                nextPending.add(change);
              }
            }
          }
          if (nextPending.length == beforeCount) {
            fail('Import loop got stuck in iteration $iteration! Seed = $seed.\nUnapplied changes: $pending');
          }
          pending = nextPending;
        }
      }

      // Compare final text states
      final finalStates = docs.map((d) {
        final textHandler = d.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        return textHandler.value;
      }).toSet();

      if (finalStates.length != 1) {
        fail('Divergence in iteration $iteration! Seed = $seed.\nStates: $finalStates');
      }
    }
  });

  group('crdt_lf - Deterministic Edge Cases', () {
    test('Anti-interleaving (Fugue Core)', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-anti');
      textA.insert(0, "Hello");

      // Sync base
      docB.importChanges(docA.exportChanges());
      final textB = docB.registeredHandlers['text-anti']! as CRDTFugueTextHandler;

      // Concurrent insertions at index 5
      textA.insert(5, " Ola");
      textB.insert(5, " World");

      // Merge changes
      final changesA = docA.exportChanges();
      final changesB = docB.exportChanges();

      docA.importChanges(changesB);
      docB.importChanges(changesA);

      expect(textA.value, textB.value);
      final finalVal = textA.value;
      // Should not be interleaved, words must remain contiguous
      expect(
        finalVal == "Hello Ola World" || finalVal == "Hello World Ola",
        true,
        reason: 'Interleaved result detected: $finalVal',
      );
    });

    test('Concurrent Overlapping Deletes', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-delete');
      textA.insert(0, "The quick brown fox jumps over the lazy dog");

      // Sync base
      docB.importChanges(docA.exportChanges());
      final textB = docB.registeredHandlers['text-delete']! as CRDTFugueTextHandler;

      // Client A deletes indices 4 to 16 ("quick brown ")
      textA.delete(4, 12);

      // Client B deletes indices 10 to 20 ("brown fox ju")
      textB.delete(10, 12);

      // Merge changes
      final changesA = docA.exportChanges();
      final changesB = docB.exportChanges();

      docA.importChanges(changesB);
      docB.importChanges(changesA);

      expect(textA.value, textB.value);
      expect(textA.value, "The mps over the lazy dog");
    });

    test('Idempotency / Double Application', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-idem');
      textA.insert(0, "Base");

      docB.importChanges(docA.exportChanges());
      final textB = docB.registeredHandlers['text-idem']! as CRDTFugueTextHandler;

      textA.insert(4, " Edit");
      final changes = docA.exportChanges();

      // Apply changes twice to B
      docB.importChanges(changes);
      docB.importChanges(changes);

      expect(textB.value, "Base Edit");
    });
  });
}
