import 'dart:math';
import 'package:flutter_test/flutter_test.dart';
import 'package:crdt_lf/crdt_lf.dart';

void main() {
  test('crdt_lf fuzzing convergence under shuffled and duplicated delivery', () {
    const seedEnv = String.fromEnvironment('FUZZ_SEED');
    final seed = int.tryParse(seedEnv) ?? DateTime.now().millisecondsSinceEpoch;
    final rand = Random(seed);
    print('[Fuzz] Running with seed: $seed');

    for (var iteration = 0; iteration < 1000; iteration++) {
      final base = "O rato roeu a roupa do rei de Roma.";
      
      // Initialize base text on one document
      final initPeerId = PeerId.parse('00000000-0000-4000-8000-000000000009');
      final initDoc = CRDTDocument(peerId: initPeerId)..registerDefaultFactories();
      final initHandler = CRDTFugueTextHandler(initDoc, 'text-fuzz');
      initHandler.insert(0, base);
      final initChanges = initDoc.exportChanges();

      // Setup 4 client docs and import base changes
      final docs = List.generate(4, (i) {
        final peerId = PeerId.parse('00000000-0000-4000-8000-00000000000${i}');
        final doc = CRDTDocument(peerId: peerId)..registerDefaultFactories();
        doc.importChanges(initChanges);
        return doc;
      });

      // Track baseline version vector after base initialization
      final baselines = docs.map((d) => d.getVersionVector()).toList();

      // Run local concurrent operations on each doc
      final List<Change> allChanges = [];
      for (var i = 0; i < docs.length; i++) {
        final doc = docs[i];
        final textHandler = doc.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        
        final opCount = rand.nextInt(5) + 1;
        for (var j = 0; j < opCount; j++) {
          // Pick random position to insert or delete
          final currentLen = textHandler.value.length;
          if (currentLen > 0 && rand.nextBool()) {
            // Delete
            final pos = rand.nextInt(currentLen);
            final count = rand.nextInt(min(5, currentLen - pos)) + 1;
            textHandler.delete(pos, count);
          } else {
            // Insert
            final pos = rand.nextInt(currentLen + 1);
            final text = String.fromCharCodes(
              List.generate(rand.nextInt(5) + 1, (_) => rand.nextInt(26) + 97)
            );
            textHandler.insert(pos, text);
          }
        }
        // Export changes generated by this client since the baseline
        allChanges.addAll(doc.exportChanges(fromVersionVector: baselines[i]));
      }

      // Simulate network delivery: shuffle changes
      allChanges.shuffle(rand);

      // Apply changes to each document in different orders (shuffled per document)
      for (final doc in docs) {
        final docChanges = List<Change>.from(allChanges)..shuffle(rand);
        // Duplicate changes to simulate at-least-once delivery (idempotency check)
        final duplicatedChanges = <Change>[];
        for (final change in docChanges) {
          duplicatedChanges.add(change);
          duplicatedChanges.add(change);
        }

        // Apply changes one by one. Since delivery is shuffled, some changes
        // might arrive before their dependencies and be skipped. We retry
        // applying pending changes until all are successfully imported.
        var pending = List<Change>.from(duplicatedChanges);
        while (pending.isNotEmpty) {
          final beforeCount = pending.length;
          final nextPending = <Change>[];
          for (final change in pending) {
            final applied = doc.importChanges([change]);
            if (applied == 0) {
              final vv = doc.getVersionVector();
              final clock = vv[change.author];
              final alreadyHas = clock != null && change.hlc.compareTo(clock) <= 0;
              if (!alreadyHas) {
                nextPending.add(change);
              }
            }
          }
          if (nextPending.length == beforeCount) {
            fail('Import loop got stuck in iteration $iteration! Seed = $seed.\nUnapplied changes: $pending');
          }
          pending = nextPending;
        }
      }

      // Compare final text states
      final finalStates = docs.map((d) {
        final textHandler = d.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        return textHandler.value;
      }).toSet();

      if (finalStates.length != 1) {
        fail('Divergence in iteration $iteration! Seed = $seed.\nStates: $finalStates');
      }
    }
  });

  group('crdt_lf - Deterministic Edge Cases', () {
    test('Anti-interleaving (Fugue Core)', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();
      final docC = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000003'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-anti');
      textA.insert(0, "Hello");

      // Sync base
      final baseChanges = docA.exportChanges();
      docB.importChanges(baseChanges);
      final textB = docB.registeredHandlers['text-anti']! as CRDTFugueTextHandler;

      CRDTFugueTextHandler(docC, 'text-anti');
      docC.importChanges(baseChanges);
      final textC = docC.registeredHandlers['text-anti']! as CRDTFugueTextHandler;

      // Capture version vectors before concurrent edits
      final vvA = docA.getVersionVector();
      final vvB = docB.getVersionVector();

      // Concurrent insertions at index 5
      textA.insert(5, " Ola");
      textB.insert(5, " World");

      // Merge changes
      final newChangesA = docA.exportChanges(fromVersionVector: vvA);
      final newChangesB = docB.exportChanges(fromVersionVector: vvB);

      docA.importChanges(newChangesB);
      docB.importChanges(newChangesA);

      // docC imports the same concurrent changes in a shuffled/shuffled order
      docC.importChanges(newChangesA);
      docC.importChanges(newChangesB);

      expect(textA.value, textB.value);
      expect(textC.value, textA.value); // Confirm all replicas converge to the exact same string
      final finalVal = textA.value;
      // Should not be interleaved, words must remain contiguous
      expect(
        finalVal,
        anyOf('Hello Ola World', 'Hello World Ola'),
        reason: 'Interleaved result detected: $finalVal',
      );
    });

    test('Concurrent Overlapping Deletes', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-delete');
      textA.insert(0, "The quick brown fox jumps over the lazy dog");

      // Sync base
      docB.importChanges(docA.exportChanges());
      final textB = docB.registeredHandlers['text-delete']! as CRDTFugueTextHandler;

      // Client A deletes indices 4 to 16 ("quick brown ")
      textA.delete(4, 12);

      // Client B deletes indices 10 to 22 ("brown fox ju")
      textB.delete(10, 12);

      // Merge changes
      final changesA = docA.exportChanges();
      final changesB = docB.exportChanges();

      docA.importChanges(changesB);
      docB.importChanges(changesA);

      expect(textA.value, textB.value);
      expect(textA.value, "The mps over the lazy dog");
    });

    test('Idempotency / Double Application', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-idem');
      textA.insert(0, "Base");

      docB.importChanges(docA.exportChanges());
      final textB = docB.registeredHandlers['text-idem']! as CRDTFugueTextHandler;

      textA.insert(4, " Edit");
      final changes = docA.exportChanges();

      // Apply changes twice to B
      docB.importChanges(changes);
      docB.importChanges(changes);

      expect(textB.value, "Base Edit");
      expect(textB.value, textA.value);
    });

    test('Out-of-order causal delivery', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-ooo');
      
      // Step 1: Insert "A" (parent)
      textA.insert(0, "A");
      final changes1 = docA.exportChanges();
      final vvAfterA = docA.getVersionVector();

      // Step 2: Insert "B" (child, causally depends on the state with "A")
      textA.insert(1, "B");
      final changes2 = docA.exportChanges(fromVersionVector: vvAfterA);

      // Verify that changes2 actually contains the child operation
      expect(changes2.length, 1);

      // Deliver changes2 (child) BEFORE changes1 (parent) to Doc B.
      // Option A: applyChange throws CausallyNotReadyException when dependencies are missing.
      expect(
        () => docB.applyChange(changes2.first),
        throwsA(isA<CausallyNotReadyException>()),
      );

      // Option B: importChanges skips the changes and returns 0 applied changes.
      final importedBefore = docB.importChanges(changes2);
      expect(importedBefore, 0);

      // Deliver parent (changes1)
      final importedParent = docB.importChanges(changes1);
      expect(importedParent, 1);

      // Now apply the child operation (changes2) again, which should succeed now that parent is present
      final importedChild = docB.importChanges(changes2);
      expect(importedChild, 1);

      final textB = docB.registeredHandlers['text-ooo']! as CRDTFugueTextHandler;
      expect(textB.value, "AB");
      expect(textB.value, textA.value);
    });

    test('Snapshot continuity', () {
      final docA = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000001'))..registerDefaultFactories();
      final docB = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000002'))..registerDefaultFactories();
      final docC = CRDTDocument(peerId: PeerId.parse('00000000-0000-4000-8000-000000000003'))..registerDefaultFactories();

      final textA = CRDTFugueTextHandler(docA, 'text-snap');
      textA.insert(0, "Hello");

      // Sync all to version V
      final initialChanges = docA.exportChanges();
      docB.importChanges(initialChanges);
      docC.importChanges(initialChanges);

      // Client C goes offline.
      // A and B perform edits up to V+50
      final textB = docB.registeredHandlers['text-snap']! as CRDTFugueTextHandler;
      for (var i = 0; i < 50; i++) {
        final currentLen = textA.value.length;
        textA.insert(currentLen, ".");
        final changes = docA.exportChanges();
        docB.importChanges(changes);
      }

      // Compact B history into snapshot
      final snapshotB = docB.takeSnapshot(pruneHistory: true);

      // Compact A history into snapshot
      docA.takeSnapshot(pruneHistory: true);

      // C wakes up and makes edits based on version V (offline)
      final textC = docC.registeredHandlers['text-snap']! as CRDTFugueTextHandler;
      textC.insert(5, " C");

      // C reconnects and sends its edits to the compacted B
      final changesC = docC.exportChanges();
      docB.importChanges(changesC);

      // Compacted B sends its snapshot to C.
      docC.importSnapshot(snapshotB);
      docC.reconstruct();

      // Sync A with the edits from C as well
      docA.importChanges(changesC);

      expect(textB.value, textA.value);
      expect(textC.value, textA.value);
    });
  });
}
