import 'dart:math';
import 'package:flutter_test/flutter_test.dart';
import 'package:crdt_lf/crdt_lf.dart';

void main() {
  test('crdt_lf fuzzing convergence under shuffled and duplicated delivery', () {
    final seed = DateTime.now().millisecondsSinceEpoch;
    final rand = Random(seed);
    print('[Fuzz] Running with seed: $seed');

    for (var iteration = 0; iteration < 1000; iteration++) {
      final base = "O rato roeu a roupa do rei de Roma.";
      
      // Setup 4 client docs
      final docs = List.generate(4, (i) {
        final peerId = PeerId.parse('00000000-0000-4000-8000-00000000000${i}');
        final doc = CRDTDocument(peerId: peerId)..registerDefaultFactories();
        // Initialize a Fugue text handler on each doc
        final handler = CRDTFugueTextHandler(doc, 'text-fuzz');
        handler.insert(0, base);
        return doc;
      });

      // Run local concurrent operations on each doc
      final List<Change> allChanges = [];
      for (var i = 0; i < docs.length; i++) {
        final doc = docs[i];
        final textHandler = doc.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        
        final opCount = rand.nextInt(5) + 1;
        for (var j = 0; j < opCount; j++) {
          // Pick random position to insert or delete
          final currentLen = textHandler.value.length;
          if (currentLen > 0 && rand.nextBool()) {
            // Delete
            final pos = rand.nextInt(currentLen);
            final count = rand.nextInt(min(5, currentLen - pos)) + 1;
            textHandler.delete(pos, count);
          } else {
            // Insert
            final pos = rand.nextInt(currentLen + 1);
            final text = String.fromCharCodes(
              List.generate(rand.nextInt(5) + 1, (_) => rand.nextInt(26) + 97)
            );
            textHandler.insert(pos, text);
          }
        }
        // Export changes generated by this client
        allChanges.addAll(doc.exportChanges());
      }

      // Simulate network delivery: shuffle changes
      allChanges.shuffle(rand);

      // Apply changes to each document in different orders (shuffled per document)
      for (final doc in docs) {
        final docChanges = List<Change>.from(allChanges)..shuffle(rand);
        // Duplicate changes to simulate at-least-once delivery (idempotency check)
        final duplicatedChanges = <Change>[];
        for (final change in docChanges) {
          duplicatedChanges.add(change);
          duplicatedChanges.add(change);
        }

        // Apply changes one by one. Since delivery is shuffled, some changes
        // might arrive before their dependencies and be skipped. We retry
        // applying pending changes until all are successfully imported.
        var pending = List<Change>.from(duplicatedChanges);
        while (pending.isNotEmpty) {
          final beforeCount = pending.length;
          final nextPending = <Change>[];
          for (final change in pending) {
            final applied = doc.importChanges([change]);
            if (applied == 0) {
              final vv = doc.getVersionVector();
              final clock = vv[change.author];
              final alreadyHas = clock != null && change.hlc.compareTo(clock) <= 0;
              if (!alreadyHas) {
                nextPending.add(change);
              }
            }
          }
          if (nextPending.length == beforeCount) {
            // If no progress was made in a full pass, we are stuck
            break;
          }
          pending = nextPending;
        }
      }

      // Compare final text states
      final finalStates = docs.map((d) {
        final textHandler = d.registeredHandlers['text-fuzz']! as CRDTFugueTextHandler;
        return textHandler.value;
      }).toSet();

      if (finalStates.length != 1) {
        fail('Divergence in iteration $iteration! Seed = $seed.\nStates: $finalStates');
      }
    }
  });
}
