// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3C5hXWmRWNQQrGn1SjxHYmbnEHI31c48',
    appId: '1:307443296345:android:51cc478b9c085021006948',
    messagingSenderId: '307443296345',
    projectId: 'supanotes-2bb99',
    storageBucket: 'supanotes-2bb99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAci9NZgBBiIBjK1n3oiMtkTWTf_PmreTw',
    appId: '1:307443296345:ios:d5cc8df1f24be1f2006948',
    messagingSenderId: '307443296345',
    projectId: 'supanotes-2bb99',
    storageBucket: 'supanotes-2bb99.firebasestorage.app',
    iosBundleId: 'com.example.supanotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZxW5UZPuY6xbkdA5ivSXZxTlmL_-pIE',
    appId: '1:307443296345:web:e8e002b3a4d6f8c2006948',
    messagingSenderId: '307443296345',
    projectId: 'supanotes-2bb99',
    authDomain: 'supanotes-2bb99.firebaseapp.com',
    storageBucket: 'supanotes-2bb99.firebasestorage.app',
  );
}
