BEGIN;

ALTER TABLE note_links
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TRIGGER update_note_links_updated_at
  BEFORE UPDATE ON note_links
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMIT;
